### ISSUE TITLE
c7n_mailer is giving me this error when I run it, any issues with the mailer itself?

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1042]
`Traceback (most recent call last):
  File "/home/anant/cloud_custodian/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 72, in main
    deploy.provision(config, functools.partial(session_factory, config))
  File "/home/anant/cloud_custodian/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 74, in provision
    archive = get_archive(config)
  File "/home/anant/cloud_custodian/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 38, in get_archive
    'memcache')
TypeError: __init__() takes at most 6 arguments (8 given)
> /home/anant/cloud_custodian/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py(38)get_archive()
-> 'memcache')
(Pdb) `

**Comment by whit537** [comment]
@JohnTheodore brought up this same issue in Gitter the other day. The problem is that you have a new version of the `c7n-mailer` executable that is importing an old version of the underlying `c7n.mu` library due to the way you have custodian installed. 

(The old library has a `PythonPackageArchive` class that took at most six arguments. The new version of `PythonPackageArchive` takes an arbitrary number of arguments, and the new mailer executable wants to give it eight.)

In @JohnTheodore's case, he "was just pip installing c7n, and git cloning to install c7n-mailer," and was able to clean up his environment and get it to work. Perhaps you could share what you did, @JohnTheodore?

Does that get you pointed in the right direction, @srinivas-anant?

**Comment by JohnTheodore** [comment]
I'll note, if we just rev c7n with a new version, it will probably fix the issue for people.

You can add `-e git+https://github.com/capitalone/cloud-custodian.git#egg=c7n` to your requirements.txt to pip install HEAD c7n from the repo to get the mu.py changes.

**Comment by srinivas-anant** [comment]
@whit537  How long will it take for the c7n.mu to be updated? I tired John's method to add the line the requirements.txt file but doesn't seem to be doing any mu.py changes.

**Comment by srinivas-anant** [comment]
Sorry my bad it was a typo error. Your answer helped me out thanks @JohnTheodore  and @whit537.

**Comment by gcetrone3** [comment]
Hi, I am new to CC. I downloaded the WHL file this morning and when I try to install get the following error.
Any thoughts?
```
H:\myFolder]> pip install c7n
Defaulting to user installation because normal site-packages is not writeable
. . .
c:\snapvolumestemp\mountpoints\{8e399ec3-0000-0000-0000-100000000000}\svroot\users\geraldcetrone\appdata\roaming\python\python39\site-packages (from c7n) (0.4.2)
Requirement already satisfied: setuptools in c:\snapvolumestemp\mountpoints\{8e399ec3-0000-0000-0000-100000000000}\svroot\program files\python39\lib\site-packages (from jsonschema==3.2.0->c7n) (57.4.0)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "C:\Program Files\Python39\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "C:\Program Files\Python39\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info
```
