### ISSUE TITLE
Boto Credentials Error in long running Container

### ISSUE THREAD

**Issue by mandeepbal** [capitalone/cloud-custodian#105]
Getting a weird Boto error when I run custodian in a container. Not sure why the credentials are not being pulled properly. The custodian run was executing multiple policies but more than halfway through policy file it just lost creds.

```
2016-05-12 01:13:58,969: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 161, in provision
    manager = LambdaManager(self.session_factory)
  File "/src/c7n/mu.py", line 195, in __init__
    self.client = self.session_factory().client('lambda')
  File "/src/c7n/credentials.py", line 37, in __call__
    self.assume_role, "CloudCustodian", session)
  File "/src/c7n/credentials.py", line 74, in assumed_session
    metadata=refresh(),
  File "/src/c7n/credentials.py", line 65, in refresh
    RoleSessionName=session_name)['Credentials']
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 142, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 126, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 124, in sign
    signer.add_auth(request=request)
  File "/usr/local/lib/python2.7/site-packages/botocore/auth.py", line 313, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/c7n/log.py", line 222, in loop
    self.send()
  File "/src/c7n/log.py", line 182, in send
    self.send_group(k, messages)
  File "/src/c7n/log.py", line 188, in send_group
    if not self.create_stream(group, stream):
  File "/src/c7n/log.py", line 173, in create_stream
    logGroupName=group, logStreamName=stream)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 142, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 126, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 124, in sign
    signer.add_auth(request=request)
  File "/usr/local/lib/python2.7/site-packages/botocore/auth.py", line 313, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials
```

**Comment by kapilt** [comment]
i just saw this occur, but its seeing this mostly after cascades of InternalFailure across an api across accounts at the same time which makes me wonder if this was an aws blip, about 8m total

**Comment by mandeepbal** [comment]
So is this not a Docker issue then?

**Comment by kapilt** [comment]
I don't see how at the moment,  we should probably setup a sandbox instance to test with and have logs for.

**Comment by kapilt** [comment]
i haven't seen any repeats of this across the fleet of installations in the past month, i'm going to close it out. if we see a reoccurence let's reopen.
