### ISSUE TITLE
Trying to filter out security groups using the ec2 schema, but I get a TypeError

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1072]
Here is my policy 

policies:
  - name: security-group-test
    resource: ec2
    comment: |
      EC2 instances that have SSH access from everywhere
    filters:
      - type: security-group
        key: cidr
        value: 0.0.0.0/0
        value_type: cidr
        op: equal

And the error output I get is this 
```2017-04-12 01:15:27,986: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/anant/cc/cc/src/c7n/c7n/policy.py", line 211, in run
    resources = self.policy.resource_manager.resources()
  File "/home/anant/cc/cc/src/c7n/c7n/resources/ec2.py", line 89, in resources
    return super(EC2, self).resources(query=query)
  File "/home/anant/cc/cc/src/c7n/c7n/query.py", line 284, in resources
    return self.filter_resources(resources)
  File "/home/anant/cc/cc/src/c7n/c7n/manager.py", line 86, in filter_resources
    resources = f.process(resources, event)
  File "/home/anant/cc/cc/src/c7n/c7n/filters/related.py", line 98, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "/home/anant/cc/cc/src/c7n/c7n/filters/related.py", line 84, in process_resource
    if self.match(robj):
  File "/home/anant/cc/cc/src/c7n/c7n/filters/core.py", line 385, in match
    v, r = self.process_value_type(self.v, r)
  File "/home/anant/cc/cc/src/c7n/c7n/filters/core.py", line 444, in process_value_type
    v = parse_cidr(value)
  File "/home/anant/cc/cc/src/c7n/c7n/utils.py", line 318, in parse_cidr
    if '/' not in value:
TypeError: argument of type 'NoneType' is not iterable
2017-04-12 01:15:27,987: custodian.commands:ERROR Error while executing policy security-group-test, continuing
Traceback (most recent call last):
  File "/home/anant/cc/cc/src/c7n/c7n/commands.py", line 178, in run
    policy()
  File "/home/anant/cc/cc/src/c7n/c7n/policy.py", line 569, in __call__
    return PullMode(self).run()
  File "/home/anant/cc/cc/src/c7n/c7n/policy.py", line 211, in run
    resources = self.policy.resource_manager.resources()
  File "/home/anant/cc/cc/src/c7n/c7n/resources/ec2.py", line 89, in resources
    return super(EC2, self).resources(query=query)
  File "/home/anant/cc/cc/src/c7n/c7n/query.py", line 284, in resources
    return self.filter_resources(resources)
  File "/home/anant/cc/cc/src/c7n/c7n/manager.py", line 86, in filter_resources
    resources = f.process(resources, event)
  File "/home/anant/cc/cc/src/c7n/c7n/filters/related.py", line 98, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "/home/anant/cc/cc/src/c7n/c7n/filters/related.py", line 84, in process_resource
    if self.match(robj):
  File "/home/anant/cc/cc/src/c7n/c7n/filters/core.py", line 385, in match
    v, r = self.process_value_type(self.v, r)
  File "/home/anant/cc/cc/src/c7n/c7n/filters/core.py", line 444, in process_value_type
    v = parse_cidr(value)
  File "/home/anant/cc/cc/src/c7n/c7n/utils.py", line 318, in parse_cidr
    if '/' not in value:
TypeError: argument of type 'NoneType' is not iterable
```

What seems to be the issue?  @kapilt @jaredsmith

**Comment by scotwk** [comment]
@srinivas-anant - use triple backquotes for a multi-line snippet.

The error message isn't very helpful, but the problem is that the key `cidr` does not exist in the information returned.  Here is the relevant subset of info I got back when I tried your policy:

```
 u'IpPermissions': [{u'FromPort': 22,
                     u'IpProtocol': 'tcp',
                     u'IpRanges': [{u'CidrIp': '0.0.0.0/0'}],
                     u'Ipv6Ranges': [],
                     u'PrefixListIds': [],
                     u'ToPort': 22,
                     u'UserIdGroupPairs': []}],
 u'IpPermissionsEgress': [{u'IpProtocol': '-1',
                           u'IpRanges': [{u'CidrIp': '0.0.0.0/0'}],
                           u'Ipv6Ranges': [],
                           u'PrefixListIds': [],
                           u'UserIdGroupPairs': []}],
```

**Comment by srinivas-anant** [comment]
Thank you @scotwk.
