### ISSUE TITLE
Error when passing values through python script

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1106]
I am running the custodian commands through a python script on an instance and I am using cache option to distinguish between multiple accounts but when I run the python script this is the error I get

```Traceback (most recent call last):
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.23.2', 'console_scripts', 'custodian')()
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/cli.py", line 339, in main
    command(options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/commands.py", line 51, in _load_policies
    collection = policy_load(options, file)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 64, in load
    return PolicyCollection(data, options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 77, in __init__
    Policy(p, options, session_factory=self.test_session_factory()))
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 490, in __init__
    self.resource_manager = self.get_resource_manager()
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 587, in get_resource_manager
    return factory(self.ctx, self.data)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/resources/ec2.py", line 81, in __init__
    super(EC2, self).__init__(ctx, data)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/query.py", line 247, in __init__
    super(QueryResourceManager, self).__init__(data, options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/manager.py", line 38, in __init__
    self._cache = cache.factory(self.ctx.options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/cache.py", line 31, in factory
    if not config.cache or not config.cache_period:
AttributeError: 'Namespace' object has no attribute 'cache_period'```

What is causing this to happen?

**Comment by scotwk** [comment]
@srinivas-anant - what arguments are you passing?

**Comment by srinivas-anant** [comment]
I figured out the error when passing the "--cache" option when doing a custodian run the "--cache-period"  option must also be passed.

**Comment by scotwk** [comment]
@srinivas-anant - if that is true then it should produce a better error message than a traceback.  But I can't reproduce:

```
$ custodian run -s out -f ~/.cache/foo.cache policies/ec2.yml
2017-04-29 20:28:10,638: custodian.policy:INFO Running policy ec2-running-instances resource: ec2 region:us-east-1 c7n:0.8.23.2
2017-04-29 20:28:10,639: custodian.policy:INFO policy: ec2-running-instances resource:ec2 has count:3 time:0.00
```

What was your command line call?

**Comment by srinivas-anant** [comment]
When running cloud custodian from an instance for cross accounts if I pass the CLI as:

`$ custodian run -d policy.yml -s out -- cache-period=15 --cache=/home/ec2-user/.cache/accountname --assume role_name --region us-east-1
2017-05-02 11:34:16,020: custodian.policy:INFO Running policy ec2-tag-compliance resource: ec2 region:us-east-1 c7n:0.8.23.2
2017-05-02 11:34:18,653: custodian.policy:INFO policy: ec2-tag-compliance resource:ec2 has count:10 time:2.62` 

But if i do not provide the _--cache-period_ option when running custodian I get this error:

`$ custodian run -d policy.yml -s out --cache-period=15 --cache=/home/ec2-user/.cache/accountname --assume role_name --region us-east-1
File "/home/ec2-user/cloud_custodian/cloud_custodian_env/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.23.2', 'console_scripts', 'custodian')()
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/cli.py", line 339, in main
    command(options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/commands.py", line 51, in _load_policies
    collection = policy_load(options, file)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 64, in load
    return PolicyCollection(data, options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 77, in __init__
    Policy(p, options, session_factory=self.test_session_factory()))
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 490, in __init__
    self.resource_manager = self.get_resource_manager()
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/policy.py", line 587, in get_resource_manager
    return factory(self.ctx, self.data)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/resources/ec2.py", line 81, in __init__
    super(EC2, self).__init__(ctx, data)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/query.py", line 247, in __init__
    super(QueryResourceManager, self).__init__(data, options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/manager.py", line 38, in __init__
    self._cache = cache.factory(self.ctx.options)
  File "/home/ec2-user/cloud_custodian/cloud_custodian_env/src/c7n/c7n/cache.py", line 31, in factory
    if not config.cache or not config.cache_period:
AttributeError: 'Namespace' object has no attribute 'cache_period'`

**Comment by scotwk** [comment]
@srinivas-anant - I'm confused.  You say you don't pass the `--cache-period` option in the 2nd example, but you do.  The only difference in your two command lines is that you have a space in `-- cache-period` in the first one.

```
custodian run -d policy.yml -s out -- cache-period=15 --cache=/home/ec2-user/.cache/accountname --assume role_name --region us-east-1

custodian run -d policy.yml -s out --cache-period=15 --cache=/home/ec2-user/.cache/accountname --assume role_name --region us-east-1
```

(Also, triple backquotes are your friend for formatting multi-line text)

**Comment by srinivas-anant** [comment]
Oh my bad. I edited it.
