### ISSUE TITLE
ClientError: An error occurred (InvalidParameterCombination) when calling the DeleteDBInstance operation: FinalDBSnapshotIdentifier can not be specified when deleting a cluster instance

### ISSUE THREAD

**Issue by victorh3** [capitalone/cloud-custodian#1153]
2017-05-11 11:06:58,017: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 241, in run
    results = a.process(resources)
  File "/usr/lib/python2.7/site-packages/c7n/resources/rds.py", line 607, in process
    client.delete_db_instance(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterCombination) when calling the DeleteDBInstance operation: FinalDBSnapshotIdentifier can not be specified when deleting a cluster instance

**Comment by kapilt** [comment]
thanks for the bug report.

this should be getting filtered out by the _db_instance_eligible_for_final_snapshot but it looks like the condition using its output has a logic flaw.

**Comment by victorh3** [comment]
Error appeared when I was trying to delete Aurora instances
