### ISSUE TITLE
Security group from config needs normalization on ingress/egress permissions

### ISSUE THREAD

**Issue by MichaelLiZhou** [capitalone/cloud-custodian#1221]
This keeps on getting invoked when running a config rule with the following policy:

```
    resource: security-group
    filters:
      - type: ingress
        Cidr:
          value: 0.0.0.0/0
          op: eq
          value_type: cidr
      - type: ingress
        Ports: [23]
    mode:
      type: config-rule
    actions:
      - type: remove-permissions
        egress: matched
```

```
argument of type 'NoneType' is not iterable: TypeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 86, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 579, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 489, in run
resources = super(ConfigRuleMode, self).run(event, lambda_context)
File "/var/task/c7n/policy.py", line 387, in run
resources, event)
File "/var/task/c7n/manager.py", line 86, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/vpc.py", line 692, in process
return super(SGPermission, self).process(resources, event)
File "/var/task/c7n/filters/core.py", line 161, in process
return filter(self, resources)
File "/var/task/c7n/resources/vpc.py", line 775, in __call__
cidr_found = self.process_cidrs(perm)
File "/var/task/c7n/resources/vpc.py", line 718, in process_cidrs
found = vf(ip_range)
File "/var/task/c7n/filters/core.py", line 330, in __call__
matched = self.match(i)
File "/var/task/c7n/filters/core.py", line 386, in match
v, r = self.process_value_type(self.v, r)
File "/var/task/c7n/filters/core.py", line 445, in process_value_type
v = parse_cidr(value)
File "/var/task/c7n/utils.py", line 325, in parse_cidr
if '/' not in value:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kapilt** [comment]
could you include or gist a sanitized (no account id) version of the config event as well

**Comment by MichaelLiZhou** [comment]
Here is the event. 
```
{
    "configRuleId": "config-rule-ze67a5",
    "version": "1.0",
    "configRuleName": "custodian-SecurityGroupIdentifierConfig",
    "configRuleArn": "arn:aws:config:us-east-1:**********:config-rule/config-rule-ze67a5",
    "invokingEvent": "{\"configurationItemDiff\":null,\"configurationItem\":{\"relatedEvents\":[\"e76ce5dd-fc23-41d5-9a56-9b9b7288095c\"],\"relationships\":[{\"resourceId\":\"eni-**********\",\"resourceName\":null,\"resourceType\":\"AWS::EC2::NetworkInterface\",\"name\":\"Is associated with NetworkInterface\"},{\"resourceId\":\"i-**********\",\"resourceName\":null,\"resourceType\":\"AWS::EC2::Instance\",\"name\":\"Is associated with Instance\"},{\"resourceId\":\"vpc-4c39712a\",\"resourceName\":null,\"resourceType\":\"AWS::EC2::VPC\",\"name\":\"Is contained in Vpc\"}],\"configuration\":{\"ownerId\":\"**********\",\"groupName\":\"Eclipse Che powered by Bitnami-5.9.1-0 on Ubuntu 14.04.3-AutogenByAWSMP-\",\"groupId\":\"sg-b4d493ca\",\"description\":\"This security group was generated by AWS Marketplace and is based on recommended settings for Eclipse Che powered by Bitnami version 5.9.1-0 on Ubuntu 14.04.3 provided by Bitnami\",\"ipPermissions\":[{\"ipProtocol\":\"tcp\",\"fromPort\":23,\"toPort\":23,\"userIdGroupPairs\":[],\"ipv6Ranges\":[],\"prefixListIds\":[],\"ipv4Ranges\":[{\"cidrIp\":\"0.0.0.0/0\"}],\"ipRanges\":[\"0.0.0.0/0\"]}],\"ipPermissionsEgress\":[{\"ipProtocol\":\"-1\",\"userIdGroupPairs\":[],\"ipv6Ranges\":[],\"prefixListIds\":[],\"ipv4Ranges\":[{\"cidrIp\":\"0.0.0.0/0\"}],\"ipRanges\":[\"0.0.0.0/0\"]}],\"vpcId\":\"vpc-**********\",\"tags\":[{\"key\":\"ComplianceStatus\",\"value\":\"No\"},{\"key\":\"Name\",\"value\":\"\"}]},\"supplementaryConfiguration\":{},\"tags\":{\"ComplianceStatus\":\"No\",\"Name\":\"\"},\"configurationItemVersion\":\"1.2\",\"configurationItemCaptureTime\":\"2017-05-25T14:46:10.911Z\",\"configurationStateId\":1495723570911,\"awsAccountId\":\"**********\",\"configurationItemStatus\":\"OK\",\"resourceType\":\"AWS::EC2::SecurityGroup\",\"resourceId\":\"sg-**********\",\"resourceName\":null,\"ARN\":\"arn:aws:ec2:us-east-1:**********:security-group/sg-**********\",\"awsRegion\":\"us-east-1\",\"availabilityZone\":\"Not Applicable\",\"configurationStateMd5Hash\":\"**********\",\"resourceCreationTime\":null},\"notificationCreationTime\":\"2017-05-26T11:00:18.875Z\",\"messageType\":\"ConfigurationItemChangeNotification\",\"recordVersion\":\"1.2\"}",
    "eventLeftScope": false,
    "debug": true,
    "executionRoleArn": "arn:aws:iam::**********:role/service-role/config-role-us-east-1",
    "accountId": "**********"
}
```

**Comment by MichaelLiZhou** [comment]
Hope this helps the debugging process but the config rule does not identify all my SGs in the region which i find odd. When i do dryruns it will say something similar to 4 filtered down to 1 or 2. But when i check the config rule it says 2 of my SGs are compliant ignoring the others.

**Comment by kapilt** [comment]
thanks, it looks like config is doing some odd mangling here, it adds a new key Ipv4Ranges with the the dict list of CidrIp, but on the default attribute of IpRanges it mangles out the CidrIp which is causing the error. its probably worthwhile to roll this into #907 pull request which is handling some of the other config oddities.

**Comment by MichaelLiZhou** [comment]
So the lambda function did some ETL to the original event?

**Comment by kapilt** [comment]
just T from EL. config has a different internal representation then say the ec2 api.
