### ISSUE TITLE
filter 'skip-ami-snapshots'  is not valid under any of the given schemas

### ISSUE THREAD

**Issue by damdr** [capitalone/cloud-custodian#1254]
Hi 

With this simple policy below : 
```
policies:
  - name: delete-stale-snapshots
    resource: ebs-snapshots
    filters:
      - type: age
        days: 28
        op: ge
      - skip-ami-snapshots: true
```

from http://www.capitalone.io/cloud-custodian/docs/_modules/c7n/resources/ebs.html
 i get this error : 
```

Traceback (most recent call last):
  File "./cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/damien/Documents/d2si/renault-digital/custodian/cloud-custodian/c7n/cli.py", line 369, in main
    command(options)
  File "/Users/damien/Documents/d2si/renault-digital/custodian/cloud-custodian/c7n/commands.py", line 55, in _load_policies
    collection = policy_load(options, fp, vars=vars)
  File "/Users/damien/Documents/d2si/renault-digital/custodian/cloud-custodian/c7n/policy.py", line 63, in load
    raise Exception("Failed to validate on policy %s \n %s" % (errors[1], errors[0]))
Exception: Failed to validate on policy delete-stale-snapshots 
 {'resource': 'ebs-snapshots', 'name': 'delete-stale-snapshots', 'filters': [{'type': 'age', 'days': 28, 'op': 'ge'}, {'skip-ami-snapshots': True}]} is not valid under any of the given schemas
Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/datapipeline/policy'},
               {'$ref': '#/definitions/resources/firehose/policy'},
               {'$ref': '#/definitions/resources/rds-cluster-snapshot/policy'},
               {'$ref': '#/definitions/resources/event-rule/policy'},
               {'$ref': '#/definitions/resources/elb/policy'},
               {'$ref': '#/definitions/resources/redshift-snapshot/policy'},
               {'$ref': '#/definitions/resources/rds-subnet-group/policy'},
               {'$ref': '#/definitions/resources/route-table/policy'},
               {'$ref': '#/definitions/resources/internet-gateway/policy'},
               {'$ref': '#/definitions/resources/ami/policy'},
               {'$ref': '#/definitions/resources/cache-cluster/policy'},
               {'$ref': '#/definitions/resources/kinesis/policy'},
               {'$ref': '#/definitions/resources/network-acl/policy'},
               {'$ref': '#/definitions/resources/snowball/policy'},
               {'$ref': '#/definitions/resources/support-case/policy'},
               {'$ref': '#/definitions/resources/ml-model/policy'},
               {'$ref': '#/definitions/resources/network-addr/policy'},
               {'$ref': '#/definitions/resources/asg/policy'},
               {'$ref': '#/definitions/resources/emr/policy'},
               {'$ref': '#/definitions/resources/kinesis-analytics/policy'},
               {'$ref': '#/definitions/resources/iam-user/policy'},
               {'$ref': '#/definitions/resources/cfn/policy'},
               {'$ref': '#/definitions/resources/vpn-gateway/policy'},
               {'$ref': '#/definitions/resources/dynamodb-stream/policy'},
               {'$ref': '#/definitions/resources/app-elb/policy'},
               {'$ref': '#/definitions/resources/ec2/policy'},
               {'$ref': '#/definitions/resources/ebs/policy'},
               {'$ref': '#/definitions/resources/storage-gateway/policy'},
               {'$ref': '#/definitions/resources/rds-cluster/policy'},
               {'$ref': '#/definitions/resources/hsm-client/policy'},
               {'$ref': '#/definitions/resources/opswork-stack/policy'},
               {'$ref': '#/definitions/resources/kms/policy'},
               {'$ref': '#/definitions/resources/log-group/policy'},
               {'$ref': '#/definitions/resources/hostedzone/policy'},
               {'$ref': '#/definitions/resources/rds-subscription/policy'},
               {'$ref': '#/definitions/resources/hsm/policy'},
               {'$ref': '#/definitions/resources/identity-pool/policy'},
               {'$ref': '#/definitions/resources/ecr/policy'},
               {'$ref': '#/definitions/resources/codebuild/policy'},
               {'$ref': '#/definitions/resources/directconnect/policy'},
               {'$ref': '#/definitions/resources/distribution/policy'},
               {'$ref': '#/definitions/resources/rds/policy'},
               {'$ref': '#/definitions/resources/key-pair/policy'},
               {'$ref': '#/definitions/resources/app-elb-target-group/policy'},
               {'$ref': '#/definitions/resources/elasticsearch/policy'},
               {'$ref': '#/definitions/resources/ecs/policy'},
               {'$ref': '#/definitions/resources/iam-group/policy'},
               {'$ref': '#/definitions/resources/batch-compute/policy'},
               {'$ref': '#/definitions/resources/redshift/policy'},
               {'$ref': '#/definitions/resources/vpn-connection/policy'},
               {'$ref': '#/definitions/resources/iam-role/policy'},
               {'$ref': '#/definitions/resources/batch-definition/policy'},
               {'$ref': '#/definitions/resources/dynamodb-table/policy'},
               {'$ref': '#/definitions/resources/hsm-hapg/policy'},
               {'$ref': '#/definitions/resources/waf/policy'},
               {'$ref': '#/definitions/resources/shield-protection/policy'},
               {'$ref': '#/definitions/resources/cache-subnet-group/policy'},
               {'$ref': '#/definitions/resources/snowball-cluster/policy'},
               {'$ref': '#/definitions/resources/iam-profile/policy'},
               {'$ref': '#/definitions/resources/vpc/policy'},
               {'$ref': '#/definitions/resources/codepipeline/policy'},
               {'$ref': '#/definitions/resources/step-machine/policy'},
               {'$ref': '#/definitions/resources/account/policy'},
               {'$ref': '#/definitions/resources/security-group/policy'},
               {'$ref': '#/definitions/resources/rest-api/policy'},
               {'$ref': '#/definitions/resources/acm-certificate/policy'},
               {'$ref': '#/definitions/resources/customer-gateway/policy'},
               {'$ref': '#/definitions/resources/codecommit/policy'},
               {'$ref': '#/definitions/resources/gamelift-fleet/policy'},
               {'$ref': '#/definitions/resources/opswork-cm/policy'},
               {'$ref': '#/definitions/resources/simpledb/policy'},
               {'$ref': '#/definitions/resources/waf-regional/policy'},
               {'$ref': '#/definitions/resources/cloudtrail/policy'},
               {'$ref': '#/definitions/resources/cache-snapshot/policy'},
               {'$ref': '#/definitions/resources/cloudsearch/policy'},
               {'$ref': '#/definitions/resources/rrset/policy'},
               {'$ref': '#/definitions/resources/peering-connection/policy'},
               {'$ref': '#/definitions/resources/streaming-distribution/policy'},
               {'$ref': '#/definitions/resources/s3/policy'},
               {'$ref': '#/definitions/resources/eni/policy'},
               {'$ref': '#/definitions/resources/efs/policy'},
               {'$ref': '#/definitions/resources/redshift-subnet-group/policy'},
               {'$ref': '#/definitions/resources/iam-certificate/policy'},
               {'$ref': '#/definitions/resources/gamelift-build/policy'},
               {'$ref': '#/definitions/resources/user-pool/policy'},
               {'$ref': '#/definitions/resources/rds-snapshot/policy'},
               {'$ref': '#/definitions/resources/shield-attack/policy'},
               {'$ref': '#/definitions/resources/launch-config/policy'},
               {'$ref': '#/definitions/resources/subnet/policy'},
               {'$ref': '#/definitions/resources/sqs/policy'},
               {'$ref': '#/definitions/resources/healthcheck/policy'},
               {'$ref': '#/definitions/resources/kms-key/policy'},
               {'$ref': '#/definitions/resources/sns/policy'},
               {'$ref': '#/definitions/resources/iam-policy/policy'},
               {'$ref': '#/definitions/resources/ebs-snapshot/policy'},
               {'$ref': '#/definitions/resources/health-event/policy'},
               {'$ref': '#/definitions/resources/alarm/policy'},
               {'$ref': '#/definitions/resources/r53domain/policy'},
               {'$ref': '#/definitions/resources/glacier/policy'},
               {'$ref': '#/definitions/resources/directory/policy'},
               {'$ref': '#/definitions/resources/lambda/policy'}]}

On instance['policies'][0]:
    {'filters': [{'days': 28, 'op': 'ge', 'type': 'age'},
                 {'skip-ami-snapshots': True}],
     'name': 'delete-stale-snapshots',
     'resource': 'ebs-snapshots'}
```

**Comment by kapilt** [comment]
bad doc example it looks like on the doc string, the shorthand syntax of k: v is reserved for value type filters on the resource attributes. other filter types need to be explicitly declared or implicit if done with no parameters.

ie.

```
policies:
  - name: delete-stale-snapshots
    resource: ebs-snapshots
    filters
       - type: age
          days: 28
          op: ge
       - skip-ami-snapshots
```

or explicit

```
policies:
  - name: delete-stale-snapshots
    resource: ebs-snapshots
    filters
       - type: age
          days: 28
          op: ge
       - type: skip-ami-snapshots
          value: false
```

**Comment by damdr** [comment]
Thank you
