### ISSUE TITLE
Lambda Traceback

### ISSUE THREAD

**Issue by SrikanthSoma** [capitalone/cloud-custodian#1304]
local variable 'resources' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 105, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 636, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 563, in run
return resources
UnboundLocalError: local variable 'resources' referenced before assignment

**Comment by kapilt** [comment]
thanks for reporting, looks like for config rules, on certain evaluations we need to set a default on resources
