### ISSUE TITLE
validate aws config rule supported resource type

### ISSUE THREAD

**Issue by r0fls** [capitalone/cloud-custodian#1319]
When deploying a policy using a lambda function with config rules I get the below error:

```
$ custodian run -s /out /cfg/docker/lambda.yml           
2017-06-23 18:40:35,561: custodian.policy:INFO Provisioning policy lambda delete-untagged-elb
2017-06-23 18:40:36,126: custodian.lambda:INFO Publishing custodian policy lambda function custodian-delete-untagged-elb
2017-06-23 18:40:42,073: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 470, in provision
    role=self.policy.options.assume_role)
  File "/src/c7n/mu.py", line 237, in publish
    if e.add(func):
  File "/src/c7n/mu.py", line 1272, in add
    params = self.get_rule_params(func)
  File "/src/c7n/mu.py", line 1240, in get_rule_params
    config_type = manager.get_model().config_type
AttributeError: type object 'resource_type' has no attribute 'config_type'
2017-06-23 18:40:42,074: custodian.commands:ERROR Error while executing policy delete-untagged-elb, continuing
Traceback (most recent call last):
  File "/src/c7n/commands.py", line 212, in run
    policy()
  File "/src/c7n/policy.py", line 672, in __call__
    resources = mode.provision()
  File "/src/c7n/policy.py", line 470, in provision
    role=self.policy.options.assume_role)
  File "/src/c7n/mu.py", line 237, in publish
    if e.add(func):
  File "/src/c7n/mu.py", line 1272, in add
    params = self.get_rule_params(func)
  File "/src/c7n/mu.py", line 1240, in get_rule_params
    config_type = manager.get_model().config_type
AttributeError: type object 'resource_type' has no attribute 'config_type'
```

It works when using a schedule. Here is the relevant part of my policy:

```yaml
...
    mode:
      type: config-rule
      role: arn:aws:iam::12345678910:role/iam_for_lambda
```

However merely changing it from config-rule to schedule it deploys successfully:

```yaml
...
    mode:
      type: periodic
      schedule: "rate(1 day)"
      role: arn:aws:iam::12345678910:role/iam_for_lambda
```

**Comment by r0fls** [comment]
Digging a bit I see that the elb doesn't have a config_type:

```
$ grep -r config_type c7n/resources/
c7n/resources//acm.py:        config_type = "AWS::ACM::Certificate"
c7n/resources//appelb.py:        config_type = 'AWS::ElasticLoadBalancingV2::LoadBalancer'
c7n/resources//cloudtrail.py:        config_type = "AWS::CloudTrail::Trail"
c7n/resources//ebs.py:        config_type = "AWS::EC2::Volume"
c7n/resources//ec2.py:        config_type = "AWS::EC2::Instance"
c7n/resources//iam.py:        config_type = "AWS::IAM::Group"
c7n/resources//iam.py:        config_type = "AWS::IAM::Role"
c7n/resources//iam.py:        config_type = "AWS::IAM::User"
c7n/resources//iam.py:        config_type = "AWS::IAM::Policy"
c7n/resources//rds.py:        config_type = 'AWS::RDS::DBInstance'
c7n/resources//rds.py:        config_type = "AWS::DB::EventSubscription"
c7n/resources//rds.py:        config_type = "AWS::RDS::DBSnapshot"
c7n/resources//redshift.py:        config_type = "AWS::Redshift::Cluster"
c7n/resources//redshift.py:        config_type = "AWS::Redshift::ClusterSubnetGroup"
c7n/resources//redshift.py:        config_type = "AWS::Redshift::ClusterSnapshot"
c7n/resources//s3.py:        config_type = 'AWS::S3::Bucket'
c7n/resources//vpc.py:        config_type = 'AWS::EC2::VPC'
c7n/resources//vpc.py:        config_type = 'AWS::EC2::Subnet'
c7n/resources//vpc.py:        config_type = "AWS::EC2::SecurityGroup"
c7n/resources//vpc.py:        config_type = "AWS::EC2::NetworkInterface"
c7n/resources//vpc.py:        config_type = "AWS::EC2::NetworkAcl"
c7n/resources//vpc.py:        config_type = "AWS::EC2::EIP"
c7n/resources//vpc.py:        config_type = "AWS::EC2::InternetGateway"
c7n/resources//vpc.py:        config_type = 'AWS::EC2::VPNConnection'
c7n/resources//vpc.py:        config_type = 'AWS::EC2::VPNGateway'
```

**Comment by kapilt** [comment]
if aws config doesn't support a resource type, custodian can't create an aws config rule for it. you can however create lambda policies for those resources which use cloudwatch events via cloudtrail policy mode or regular poll mode (default) type policies (lambda or otherwise).

http://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html

**Comment by kapilt** [comment]
we should be validating this better with a more validation error instead of a traceback
