### ISSUE TITLE
DynamoDB resources returned in the lambda function are strings

### ISSUE THREAD

**Issue by r0fls** [capitalone/cloud-custodian#1398]
For some reason with the lambda deployment, dynamoDb resources are being returned as strings which is raising an exception here: https://github.com/capitalone/cloud-custodian/blob/master/c7n/query.py#L94

Here's the full traceback (for the curious):

```
string indices must be integers: TypeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 109, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 650, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 428, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 412, in resolve_resources
resources = self.policy.resource_manager.get_resources(resource_ids)
File "/var/task/c7n/query.py", line 308, in get_resources
resources = self.augment(self.source.get_resources(ids))
File "/var/task/c7n/query.py", line 147, in get_resources
return self.query.get(self.manager.resource_type, ids)
File "/var/task/c7n/query.py", line 94, in get
resources = [r for r in resources if r[m.id] in identities]
TypeError: string indices must be integers
```

I have a PR I'm going to submit to fix it.

**Comment by r0fls** [comment]
By the way here is a stripped down policy that should exhibit this when deployed with lambda:

```yaml
  - name: dynamodb-policy
    resource: dynamodb-table
    description: dynamodb policy
    mode:
      type: cloudtrail
      timeout: 300
      events:
        - source: dynamodb.amazonaws.com
          event: CreateTable
          ids: "requestParameters.tableName"
      role: some_role_arn
      mode: "debug"
```

**Comment by kapilt** [comment]
the resources shouldn't be strings, this sounds like an issue in the get_resources for dynamodb resource manager. I'll have a look

**Comment by kapilt** [comment]
merged
