### ISSUE TITLE
account.filters.service-limit in regions other than us-east-1

### ISSUE THREAD

**Issue by taohungyang** [capitalone/cloud-custodian#1403]
- The filter `service-limit` and action `request-limit-increase` in resource `account` are both using the AWS Support API. 
- While resource `account` is available in multiple regions, `support` has a single endpoint in us-east-1 (but has global data).

Currently we will meet an error if we run the policy below in us-west-2
```policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
```
If we run this in us-east-1, we will get ServiceLimits information in every region. 
If we further use the action `request-limit-increase`, it could raise the limit not only for us-east-1, but for any region that has the resource hitting the threshold.

I thought of the following possible solutions but both with trade off:
1. Use us-east-1 for support client and separate the ServiceLimits information by region.
   - pros:
      - get the ServiceLimits information in the right region
      - will only increase the limit for that region
   - cons:
      - in the ServiceLimits information, IAM has no region. We could put the IAM limit information in every region. But when raising the limit, we might create duplicate cases for the same IAM limit.
   
2. Raise an error when using the filter and action in regions other than us-east-1 (Maybe mentioned in the docstring also)
   - pros:
      - No IAM problem as we can only run in one region and get global data
      - Get global data in one time and also raise the limit in every region at once
   - cons:
      - will always see error if not in us-east-1

May I know which one do you prefer, or if there is a better way to handle this? @kapilt 
Thanks!

**Comment by kapilt** [comment]
- related #1404 
- what does the error look like trying to run out of region ie not us-east-1?
- i'd like to see the raise the limit written up as a use case example for the docs, not just the inline code docs.
- let's chat on the pro/cons of the approaches, atm leaning towards 1. with a caveat of global services get an explicit validation error message and must be targeted in us-east-1 (via region: us-east-1 on the policy).

**Comment by taohungyang** [comment]
- I did discuss with Christo before and we decided to separate the tasks.
- Below is the error log:
```
2017-07-14 12:07:44,920: custodian.commands:DEBUG Loaded file limit.yaml. Contains 1 policies
2017-07-14 12:07:45,007: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:./account-service-limits>
2017-07-14 12:07:45,008: custodian.policy:DEBUG Running policy account-service-limits resource: account region:us-west-2 c7n:0.8.24.4
2017-07-14 12:07:53,501: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/thomas/cloud-custodian/c7n/policy.py", line 305, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/thomas/cloud-custodian/c7n/resources/account.py", line 65, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/thomas/cloud-custodian/c7n/manager.py", line 88, in filter_resources
    resources = f.process(resources, event)
  File "/Users/thomas/cloud-custodian/c7n/resources/account.py", line 410, in process
    checkId=self.check_id, language='en')['result']
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    operation_model, request_dict)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/thomas/cloud-custodian/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```
- will do!
- `Validating via the region on the policy` might be a good option. 
   Did think about using the validation part to handle the problem. But since I specify the region on the command instead of the policy, I wasn't able to get the region information when validating. 

   In this way, we'll put the IAM limit information only in us-east-1 and also provide the example in both docstring and usecases.

 - One more discover: In the original PR for `action: request-limit-increase` #1062 , we seems to drop IAM in this action. (But still we are able to query IAM information from `filter: service-limit`) Do we want to keep in this way?

**Comment by taohungyang** [comment]
Solved. PR merged.
