### ISSUE TITLE
Credential report failing 

### ISSUE THREAD

**Issue by jdubs** [capitalone/cloud-custodian#1427]
Hi, I just rolled out the latest cloud custodian to my env. Some iam account policy stuff appears to be breaking because of a change. It appears that this error initially appeared in pr #1343 

Stack trace
```
2017-07-20 13:33:21,212: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/jtrenholm/work/github-cloud-custodian/cloud-custodian-orig/c7n/policy.py", line 305, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/jtrenholm/work/github-cloud-custodian/cloud-custodian-orig/c7n/query.py", line 294, in resources
    return self.filter_resources(resources)
  File "/Users/jtrenholm/work/github-cloud-custodian/cloud-custodian-orig/c7n/manager.py", line 88, in filter_resources
    resources = f.process(resources, event)
  File "/Users/jtrenholm/work/github-cloud-custodian/cloud-custodian-orig/c7n/resources/iam.py", line 645, in process
    report = self.get_credential_report()
  File "/Users/jtrenholm/work/github-cloud-custodian/cloud-custodian-orig/c7n/resources/iam.py", line 564, in get_credential_report
    reader = csv.reader(io.StringIO(data))
TypeError: initial_value must be unicode or None, not str
2017-07-20 13:33:21,212: custodian.commands:ERROR Error while executing policy iam_accounts-notify-remove-never_used, continuing
```
Policy
```
policies:
  - name: iam_accounts-notify-remove-never_used
    description: |
       Notification for 5 days or less before removing IAM accounts that have never been used
    resource: iam-user
    filters:
      - type: credential
        key: user
        value: *whitelisted_users
        op: not-in
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 85
        op: gte
```

**Comment by jdubs** [comment]
Hmmm, it appears that this was due an error being sent from the AWS API. We were unable to figure out what the error was, but everything is working now
/shrug

**Comment by kapilt** [comment]
ugh.. py3 support definitely has caused some issues ( @whit537 ). thanks for the report.
