### ISSUE TITLE
Reports: AttributeError: type object 'resource_type' has no attribute 'date'

### ISSUE THREAD

**Issue by sreeramsanjay** [capitalone/cloud-custodian#1441]
unable to generate reports for resource account,
Traceback (most recent call last):
  File "/root/custodian/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.24.4', 'console_scripts', 'custodian')()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/cli.py", line 398, in main
    command(options)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 105, in _load_policies
    return f(options, list(policies))
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 239, in report
    policies, begin_date, options, sys.stdout, raw_output_fh=options.raw)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/reports/csvout.py", line 76, in report
    include_policy=len(policy_names) > 1
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/reports/csvout.py", line 160, in __init__
    if model.date:
AttributeError: type object 'resource_type' has no attribute 'date'

**Comment by scotwk** [comment]
@sreeramsanjay - I fixed it in the linked PR so you don't get a traceback anymore.  

There were no default report fields defined for the account resource, so it just shows the ID and name, which probably is not a very exciting report.  

You can use `--field` to add other fields, although for the account resource I'm not sure what there is to add.  If you think there should be a different set of defaults for this resource type then let us know.

**Comment by kapilt** [comment]
merged
