### ISSUE TITLE
Issue Installing - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Faye-E-Ellis** [capitalone/cloud-custodian#1507]
Hi, 

I'm trying to install this on Amazon linux but when I try to validate the yml file I'm getting the following Syntax error, any ideas what this could be? 
Python version is: Python 2.6.9

 custodian]# custodian validate custodian.yml                 
Traceback (most recent call last):
  File "/usr/bin/custodian/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.25.1', 'console_scripts', 'custodian')()
  File "/usr/bin/custodian/lib/python2.6/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/bin/custodian/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/bin/custodian/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/bin/custodian/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/bin/custodian/lib/python2.6/site-packages/c7n/cli.py", line 37, in <module>
    from c7n.commands import schema_completer
  File "/usr/bin/custodian/lib/python2.6/site-packages/c7n/commands.py", line 170
    conf_policy_names = {p['name'] for p in data.get('policies', ())}
                                     ^
SyntaxError: invalid syntax

**Comment by alfredgamulo** [comment]
Can you paste your yaml file for context? Are you able to update to Python 2.7, the version we support?

**Comment by kapilt** [comment]
minimum version of python for custodian is 2.7
