### ISSUE TITLE
err on s3 cloudtrail lambda policy

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#159]
reported internally, on an s3 custodian policy that was listening to create bucket event, the function fired, but had the following error:
```
string indices must be integers, not str:
TypeError Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 72, in dispatch_event p.push(event, context)
File "/var/task/c7n/policy.py", line 134, in push resources = self.resource_manager.get_resources(resource_ids)
File "/var/task/c7n/resources/s3.py", line 91, in get_resources results = filter(None, results)
File "/var/task/concurrent/futures/_base.py", line 581, in result_iterator yield future.result()
File "/var/task/concurrent/futures/_base.py", line 405, in result return self.__get_result()
File "/var/task/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs)
File "/var/task/c7n/resources/s3.py", line 146, in assemble_bucket v = method(Bucket=b['Name'])
TypeError: string indices must be integers, not str
```

**Comment by kapilt** [comment]
based on previous test data it looks like the event source for s3 changed from s3.aws to s3.amazonaws.com
