### ISSUE TITLE
lambda function failing while calling parse_cidr function of utils

### ISSUE THREAD

**Issue by kushal-sngh** [capitalone/cloud-custodian#1619]
I am trying to list all sg's which have port 22 open for 0.0.0.0/0 and send an email via config rule.
My Policy:
policies:
  - name: get_bad_sg
    mode:
      type: config-rule
      role: "arn:aws:iam::*******:role/YourRole"
    resource: security-group
    filters:
     - type: ingress
       #Ports: [22]
       Cidr:
        value: 0.0.0.0/0
        op: eq
        value_type: cidr
       #IpProtocol: tcp
       ToPort: 22
    actions:
       - type: notify
         to:
           - event-user
           - resource-creator
           - EMAIL
         template: default
         transport:
            type: sqs
            region: us-east-1
            queue: SQS queue

**Error**

argument of type 'NoneType' is not iterable: TypeError
Traceback (most recent call last):
 File "/var/task/custodian_policy.py", line 4, in run
 return handler.dispatch_event(event, context)
 File "/var/task/c7n/handler.py", line 109, in dispatch_event
 p.push(event, context)
 File "/var/task/c7n/policy.py", line 659, in push
 return mode.run(event, lambda_ctx)
 File "/var/task/c7n/policy.py", line 558, in run
 resources = super(ConfigRuleMode, self).run(event, lambda_context)
 File "/var/task/c7n/policy.py", line 439, in run
 resources, event)
 File "/var/task/c7n/manager.py", line 88, in filter_resources
 resources = f.process(resources, event)
 File "/var/task/c7n/resources/vpc.py", line 749, in process
 return super(SGPermission, self).process(resources, event)
 File "/var/task/c7n/filters/core.py", line 165, in process
 return list(filter(self, resources))
 File "/var/task/c7n/resources/vpc.py", line 832, in __call__
 cidr_found = self.process_cidrs(perm)
 File "/var/task/c7n/resources/vpc.py", line 775, in process_cidrs
 found = vf(ip_range)
 File "/var/task/c7n/filters/core.py", line 339, in __call__
 matched = self.match(i)
 File "/var/task/c7n/filters/core.py", line 395, in match
 v, r = self.process_value_type(self.v, r, i)
 File "/var/task/c7n/filters/core.py", line 456, in process_value_type
 v = parse_cidr(value)
 File "/var/task/c7n/utils.py", line 361, in parse_cidr
 if '/' not in value:
TypeError: argument of type 'NoneType' is not iterable

**Comment by kushal-sngh** [comment]
I think its failing when security-group's source is another security-group.

**Comment by kushal-sngh** [comment]
I did little more debugging by putting print statement in utils .py class and I see this in logs: 
15:48:02
CIDR Value 0.0.0.0/0
15:48:02
CIDR Value ()
15:48:02
'NoneType' object has no attribute '_version': AttributeError Traceback

**Comment by kapilt** [comment]
thanks for the bug report
