### ISSUE TITLE
install instructions for windows

### ISSUE THREAD

**Issue by MattFenner** [capitalone/cloud-custodian#1656]
Hi, 

On your getting started page it has instructions for quick install. It took me quite a while to realise these instructions are for linux and not windows.

I think it would be great if:
a) it is clearly marked that those instructions are for linux
b) have instuctions for windows.

the following seems to work for me on windows (someone who knows python better may know a nicer way?) :
`virtualenv --python=C:\Python27\python.exe custodian`
`custodian\Scripts\activate`
`pip install c7n`

edit: actually after playing a bit more it turns out that it doesn't work in windows (at least for me), i get the error when I try to do `custodian run -s . policy.yaml`:

```
2017-10-13 20:54:07,492: custodian.policy:INFO Provisioning policy lambda auto-tag-creator
2017-10-13 20:54:07,788: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\c7n\policy.py", line 507, in provision
    role=self.policy.options.assume_role)
  File "c:\python27\lib\site-packages\c7n\mu.py", line 223, in publish
    func, role, s3_uri, qualifier=alias)
  File "c:\python27\lib\site-packages\c7n\mu.py", line 335, in _create_or_update
    code_ref = {'ZipFile': archive.get_bytes()}
  File "c:\python27\lib\site-packages\c7n\mu.py", line 177, in get_bytes
    return open(self._temp_archive_file.name, 'rb').read()
IOError: [Errno 13] Permission denied: 'c:\\users\\mfenner\\appdata\\local\\temp\\tmp26lgus'
2017-10-13 20:54:07,789: custodian.commands:ERROR Error while executing policy auto-tag-creator, continuing
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\c7n\commands.py", line 216, in run
    policy()
  File "c:\python27\lib\site-packages\c7n\policy.py", line 712, in __call__
    resources = mode.provision()
  File "c:\python27\lib\site-packages\c7n\policy.py", line 507, in provision
    role=self.policy.options.assume_role)
  File "c:\python27\lib\site-packages\c7n\mu.py", line 223, in publish
    func, role, s3_uri, qualifier=alias)
  File "c:\python27\lib\site-packages\c7n\mu.py", line 335, in _create_or_update
    code_ref = {'ZipFile': archive.get_bytes()}
  File "c:\python27\lib\site-packages\c7n\mu.py", line 177, in get_bytes
    return open(self._temp_archive_file.name, 'rb').read()
IOError: [Errno 13] Permission denied: 'c:\\users\\mfenner\\appdata\\local\\temp\\tmp26lgus'
```

**Comment by MattFenner** [comment]
act

**Comment by MattFenner** [comment]
I think i must have accidentally closed this. It is still relavent

**Comment by kapilt** [comment]
for windows i'd recommend docker, for install we work well on osx and linux

**Comment by MattFenner** [comment]
Is there no plans for making it work natively in windows? This seems like a pretty big bummer for us. It seems like it was fairly close to working.

**Comment by kapilt** [comment]
It is pretty close, and we've had it working in the past, but without ci infrastructure on windows, ensuring that it continues to do so is a bit difficult. afaik the only issue with windows is the tempfile usage on lambda uploads.

given the ease of docker on windows and bash for windows, i would have hoped that would allow for ready usage of custodian as is on windows.
