### ISSUE TITLE
Evaluating policy on ElasticSearch resource failing

### ISSUE THREAD

**Issue by teo-scout24** [capitalone/cloud-custodian#1658]
```2017-10-13 19:16:09,971 - custodian.commands - ERROR - Error while executing policy elasticsearch, continuing
Traceback (most recent call last):
  File "/var/task/lib/c7n/commands.py", line 216, in run
    policy()
  File "/var/task/lib/c7n/policy.py", line 693, in __call__
    resources = PullMode(self).run()
  File "/var/task/lib/c7n/policy.py", line 305, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/lib/c7n/query.py", line 367, in resources
    resources = self.augment(self.source.resources(query))
  File "/var/task/lib/c7n/resources/elasticsearch.py", line 76, in augment
    *w.map(_augment, chunks(domains, 5))))
  File "/var/runtime/concurrent/futures/_base.py", line 605, in result_iterator
    yield future.result()
  File "/var/runtime/concurrent/futures/_base.py", line 429, in result
    return self.__get_result()
  File "/var/runtime/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/lib/c7n/resources/elasticsearch.py", line 71, in _augment
    client.list_tags, ARN=rarn).get('TagList', [])
  File "/var/task/lib/c7n/utils.py", line 331, in _retry
    return func(*args, **kw)
  File "/var/runtime/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ValidationException: An error occurred (ValidationException) when calling the ListTags operation: Invalid ARN provided. com.a9.cloudsearch.exception.CSInvalidTypeException: Invalid client-id  in arn arn:aws:es:eu-west-1::domain/test. Expected: [xxxxxxxxxxxx]

x = AWS Account ID
```

**Comment by kapilt** [comment]
hmm.. thats odd i just created an es cluster and custodian policy and ran it without issue (us-east-1).  what's your policy look like?

**Comment by kapilt** [comment]
also repeated in eu-west-1 without any issue.. also what version of custodian are you using?

**Comment by teo-scout24** [comment]
@kapilt  it's just simple policy to get all newly created es cluster, I notice when running directly on same account it works. However, if I'm running it via assume_role into other account then it fails, other resources are fine except es. I'm running version 0.8.26.0

```policies:
  - name: es-list
    resource: es
    filters:
      - "tag:NewESCluster": absent
```

**Comment by kapilt** [comment]
by `assume_role` you mean passing --assume on the the command line?

**Comment by teo-scout24** [comment]
Hi @kapilt  I'm using run() method directly from `c7n.commands`
```
    run(argparse.Namespace(
        account_id=None,
        assume_role="aws_role_arn",
        cache=None,
        cache_period=0,
        command=u'c7n.commands.run',
        config=None,
        configs=['policy.yaml'],
        debug=False,
        dryrun=True,
        external_id=None,
        log_group=None,
        metrics_enabled=False,
        output_dir='/result/',
        policy_filter=None,
        profile=None,
        quiet=None,
        regions=['eu-west-1'],
        resource_type=None,
        subparser='run',
        vars=None,
        verbose=None))
```

**Comment by kapilt** [comment]
so I think we populate account id with the correct value here when run via the cli, and your getting an issue since your using c7n as a library, which tbh is not something we support as a stable interface, although in practice its been reasonably stable. trying putting in the assumed role's account id into that namespace struct.

**Comment by teo-scout24** [comment]
It works now, thank you.
