### ISSUE TITLE
Tag error on RDS Cloudtrail policy action

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#169]
RDS Policy fires but produces the following (instance is untagged):
_rds_tags() takes exactly 5 arguments (1 given): 
TypeError Traceback (most recent call last): 
File "/var/task/custodian_policy.py", line 4, in run return handler.dispatch_event(event, context) 
File "/var/task/c7n/handler.py", line 72, in dispatch_event p.push(event, context) 
File "/var/task/c7n/policy.py", line 134, in push resources = self.resource_manager.get_resources(resource_ids) 
File "/var/task/c7n/resources/rds.py", line 124, in get_resources _rds_tags(results) 
TypeError: _rds_tags() takes exactly 5 arguments (1 given)

**Comment by kapilt** [comment]
this was resolved in 0.8.12, 0.8.13 is current release.
