### ISSUE TITLE
'source: config' errors for S3 resource

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#1691]
Policy snippet
```yml
  - name: blahblah
    resource: s3
    region: us-east-1
    source: config
    ...
```
Errors:
```
2017-10-22 11:25:17,078: policyrun:DEBUG Running policy:blahblah account:acct1 region:us-east-1
2017-10-22 11:25:44,412: custodian.resources.s3:ERROR Exception getting resources from config
 u'redirectsAllRequestsTo'
2017-10-22 11:25:44,414: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
 File "/usr/local/custodian/site-packages/c7n/policy.py", line 305, in run
  resources = self.policy.resource_manager.resources()
 File "/usr/local/custodian/site-packages/c7n/query.py", line 395, in resources
  resources = self.augment(self.source.resources(query))
 File "/usr/local/custodian/site-packages/c7n/query.py", line 305, in resources
  results.extend(f.result())
 File "/usr/local/custodian/site-packages/concurrent/futures/_base.py", line 422, in result
  return self.__get_result()
 File "/usr/local/custodian/site-packages/concurrent/futures/thread.py", line 62, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/usr/local/custodian/site-packages/c7n/query.py", line 271, in get_resources
  results.append(self.load_resource(revisions[0]))
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 152, in load_resource
  method(resource, v)
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 343, in handle_BucketWebsiteConfiguration
  'HostName': item_value['redirectsAllRequestsTo']['hostName'],
KeyError: u'redirectsAllRequestsTo'
```
```
2017-10-22 11:14:17,252: policyrun:DEBUG Running policy:blahblah account:acct1 region:us-east-1
2017-10-22 11:14:40,089: custodian.resources.s3:ERROR Exception getting resources from config
 u'CloudFunctionConfiguration'
2017-10-22 11:14:40,092: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
 File "/usr/local/custodian/site-packages/c7n/policy.py", line 305, in run
  resources = self.policy.resource_manager.resources()
 File "/usr/local/custodian/site-packages/c7n/query.py", line 395, in resources
  resources = self.augment(self.source.resources(query))
 File "/usr/local/custodian/site-packages/c7n/query.py", line 305, in resources
  results.extend(f.result())
 File "/usr/local/custodian/site-packages/concurrent/futures/_base.py", line 422, in result
  return self.__get_result()
 File "/usr/local/custodian/site-packages/concurrent/futures/thread.py", line 62, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/usr/local/custodian/site-packages/c7n/query.py", line 271, in get_resources
  results.append(self.load_resource(revisions[0]))
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 152, in load_resource
  method(resource, v)
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 287, in handle_BucketNotificationConfiguration
  d.setdefault(self.NotifyTypeMap[n['type']], []).append(ninfo)
KeyError: u'CloudFunctionConfiguration'
```
```
2017-10-22 10:59:24,309: policyrun:DEBUG Running policy:blahblah account:acct1 region:us-east-1
2017-10-22 10:59:28,550: custodian.resources.s3:ERROR Exception getting resources from config
 'NoneType' object is not subscriptable
2017-10-22 10:59:28,551: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
 File "/usr/local/custodian/site-packages/c7n/policy.py", line 305, in run
  resources = self.policy.resource_manager.resources()
 File "/usr/local/custodian/site-packages/c7n/query.py", line 395, in resources
  resources = self.augment(self.source.resources(query))
 File "/usr/local/custodian/site-packages/c7n/query.py", line 305, in resources
  results.extend(f.result())
 File "/usr/local/custodian/site-packages/concurrent/futures/_base.py", line 422, in result
  return self.__get_result()
 File "/usr/local/custodian/site-packages/concurrent/futures/thread.py", line 62, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/usr/local/custodian/site-packages/c7n/query.py", line 271, in get_resources
  results.append(self.load_resource(revisions[0]))
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 152, in load_resource
  method(resource, v)
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 257, in handle_BucketLifecycleConfiguration
  rr['Filter'] = self.convertLifePredicate(r['filter']['predicate'])
 File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 262, in convertLifePredicate
  if p['type'] == 'LifecyclePrefixPredicate':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kapilt** [comment]
we've got a few good unit tests here but it looks like their focused on full coverage semantics, its clear we need a few more to cover some of the delta cases. The s3 config representation requires the most transformation of all the config support resources.

**Comment by kapilt** [comment]
i've been struggling to reproduce this or find an extant bucket that can trigger, lets chat to see if we can find a good test case.

**Comment by kapilt** [comment]
spoke too soon, found one for for the first case.

**Comment by kapilt** [comment]
wasn't able to find the lambda function config issue, but added an appropriate remapping, let's chat if you have an extant example, that one is a bit odd in that its relying on a historical capture artifact before config switched out to the newer api, so its not something that can be reproduced with a newer bucket.
