### ISSUE TITLE
c7n_mailer - Readme test - Error

### ISSUE THREAD

**Issue by stevelaver** [capitalone/cloud-custodian#1780]
Hi!

I am trying to test the c7n-mailer using the example mailer.yml and test-policy.yml in the readme. The Lambda deploys but when it runs I see the following error in the cloud watch logs:

('Unknown resource type', u'sqs')

Followed by:

[ERROR]	2017-11-13T15:02:42.369Z	b27a74a0-c883-11e7-a5ad-53eada5f2f8b	Error starting mailer MailerSqsQueueProcessor(). 
Error: unicode argument expected, got 'str' 

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 52, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 122, in run
self.process_sqs_messsage(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 148, in process_sqs_messsage
to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)
File "/var/task/c7n_mailer/email_delivery.py", line 144, in get_to_addrs_email_messages_map
list(to_addrs)
File "/var/task/c7n_mailer/email_delivery.py", line 170, in get_mimetext_message
body = get_rendered_jinja(to_addrs, sqs_message, resources, self.logger)
File "/var/task/c7n_mailer/utils.py", line 62, in get_rendered_jinja
region=sqs_message.get('region', ''))
File "/var/task/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/var/task/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/var/task/msg-templates/default.j2", line 5, in top-level template code
{{ format_resource(resource, policy['resource']) }}
File "/var/task/c7n_mailer/utils.py", line 272, in resource_format
return "%s" % format_struct(resource)
File "/var/task/c7n_mailer/utils.py", line 115, in format_struct
json.dump(evt, buf, indent=2)
File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
fp.write(chunk)
TypeError: unicode argument expected, got 'str'

Please can you help? I've attached my YAML files. 

[files.zip](https://github.com/capitalone/cloud-custodian/files/1467357/files.zip)

**Comment by stevelaver** [comment]
UPDATE: I now receive the email, SES was still in Sandbox. However, I still get the above error in cloudwatch

**Comment by kapilt** [comment]
@whit537 is this a py3 related issue?

**Comment by whit537** [comment]
@kapilt Yes, confirmed broken on `master` and fixed in https://github.com/capitalone/cloud-custodian/pull/1417. 👍

**Comment by whit537** [comment]
P.S. I added 9a0aaae852d8b770cdb63832922ec1e28a199309 to #1417 to remove the "Unknown resource type" red herring.

**Comment by mechastorm** [comment]
Note that I noticed this error as well in version 0.8.27.0.

**Comment by whit537** [comment]
Makes sense. 0.8.27.0 does not include #1417. Once we cut a new release this should go away, cf. https://github.com/capitalone/cloud-custodian/issues/1817#issuecomment-345963332.
