### ISSUE TITLE
c7n-org config file requires 'tags' to be defined, unclear as to why

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#1828]
Leaving out tags in the config file results in the following error:

```
 c7n-org run --debug -c config/accounts.yml  -a tscloud -u policies/tscloud/tag-compliance.yml  -s /tmp/c7n --region us-west-2
Traceback (most recent call last):
  File "/home/cbouscal/.local/bin/c7n-org", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cbouscal/.local/lib/python2.7/site-packages/c7n_org/cli.py", line 387, in run
    debug)] = (a, r)
  File "/usr/lib/python2.7/site-packages/c7n/executor.py", line 63, in submit
    return MainThreadFuture(func(*args, **kw))
  File "/home/cbouscal/.local/lib/python2.7/site-packages/c7n_org/cli.py", line 334, in run_account
    with environ(**account_tags(account)):
  File "/home/cbouscal/.local/lib/python2.7/site-packages/c7n_org/utils.py", line 6, in account_tags
    for t in account.get('tags'):
TypeError: 'NoneType' object is not iterable
```

**Comment by kapilt** [comment]
yeah, thats an oversight, it should be optional.

**Comment by aardvarq** [comment]
This still seems to be a problem.
