### ISSUE TITLE
Bug: "NoneType" error in `bucket-notification` filter in s3

### ISSUE THREAD

**Issue by salwandhruvdev** [capitalone/cloud-custodian#1915]
If there are no buckets, this [line](https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L878) returns AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kapilt** [comment]
thats not quite enough to go on, why is an action being invoked on a resource that doesn't exist. what's the policy here?

**Comment by jhnlsn** [comment]
Additional traceback info

```Traceback (most recent call last):
  File "/usr/local/custodian/site-packages/c7n/policy.py", line 305, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/custodian/site-packages/c7n/query.py", line 397, in resources
    return self.filter_resources(resources)
  File "/usr/local/custodian/site-packages/c7n/manager.py", line 88, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 872, in process
    return super(BucketNotificationFilter, self).process(buckets, event)
  File "/usr/local/custodian/site-packages/c7n/filters/core.py", line 358, in process
    return super(ValueFilter, self).process(resources, event)
  File "/usr/local/custodian/site-packages/c7n/filters/core.py", line 171, in process
    return list(filter(self, resources))
  File "/usr/local/custodian/site-packages/c7n/resources/s3.py", line 878, in __call__
    for config in bucket.get('Notification', {}).get(field, []):
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by salwandhruvdev** [comment]
Saw this error when running the policy in the wrong region, but shouldn't this filter return without error if there is no bucket?

**Comment by salwandhruvdev** [comment]
Are we good to work on this Bug? @kapilt @jhnlsn

**Comment by jhnlsn** [comment]
@salwandhruvdev please feel free to submit a PR

**Comment by salwandhruvdev** [comment]
I will start working on this today.

**Comment by salwandhruvdev** [comment]
I am not able to recreate this error. Will reopen this issue if I run into this error again
