### ISSUE TITLE
Error when trying to filter on the absents of a tag action configure-lifecycle resource s3

### ISSUE THREAD

**Issue by sepulworld** [capitalone/cloud-custodian#1931]
Cloud-custodian verions 0.8.27.2

Error when trying to filter on the absents of a tag action configure-lifecycle on resource s3

```  
- name: s3-set-root-prefix-cleanup-noncurrent-and-mpu
    resource: s3
    description: |
      Apply a root level prefix cleanup for NoncurrentVersionExpiration and Multipart Upload Cleanup to all s3 buckets
      except those tagged with CustomRootPrefixCleanup
    filters:
      - "tag:CustomRootPrefixCleanup": absent
    actions:
      - type: configure-lifecycle
        rules:
          - ID: Default Versioning and Multipart Upload Cleanup
            Status: Enabled
            Prefix: ""
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
```

Error:

```
2018-01-10 00:33:29,672: custodian.commands:ERROR Error while executing policy s3-set-root-prefix-cleanup-noncurrent-and-mpu, continuing
Traceback (most recent call last):
  File "/src/c7n/commands.py", line 217, in run
    policy()
  File "/src/c7n/policy.py", line 750, in __call__
    resources = mode.run()
  File "/src/c7n/policy.py", line 337, in run
    results = a.process(resources)
  File "/src/c7n/resources/s3.py", line 2586, in process
    results += filter(None, [future.result()])
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/c7n/resources/s3.py", line 2621, in process_bucket
    raise e
ClientError: An error occurred (InvalidRequest) when calling the PutBucketLifecycleConfiguration operation: Base level prefix cannot be used in Lifecycle V2, prefixes are only supported in the Filter.
```

If I remove the 

```   
 filters:
      - "tag:CustomRootPrefixCleanup": absent
```
The policy will work as intended. Curious if this is a bug, or is my policy wrong somehow?

**Comment by kapilt** [comment]
its a bug, lifecycle configuration was a recent addition.

**Comment by jhnlsn** [comment]
Hello @sepulworld, the use of `Prefix` in the root of the Rule has been deprecated as per documentation in [boto3](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_bucket_lifecycle_configuration).

you need to update your policy to reflect the changes like so

```yaml
rules:
  - ID: Test
    Filter:
      Prefix:""
```

Let me know if this helps

**Comment by kapilt** [comment]
@jhnlsn thanks for looking into this, it looks like it is indeed a deprecated api syntax issue. We're doing straight pass through on lifecycle parameters, so the underlying lifecycle rule has to be usable per the api.

**Comment by sepulworld** [comment]
Thanks @jhnlsn adjusting to use the Filter you mentioned works well!

**Comment by thibaudlf** [comment]
> 

thank you @jhnlsn
