### ISSUE TITLE
support cloud-trail lambda policies for child resources (rest-stage, ecs-task, ecs-service, rest-resource)

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1976]
The following new API Gateway policy to enable Logging on any new stage/deployment isn't working as if throws the error:

```
policies:

- name: apigw-enable-logging-from-deploy
  resource: rest-stage
  mode:
      type: cloudtrail
      events:
        - source: apigateway.amazonaws.com
          event: CreateDeployment
          ids: "requestParameters.createDeploymentInput.stageName"
  filters:
    - or:
        - 'methodSettings."*/*".loggingLevel': 'OFF'
        - 'methodSettings."*/*".loggingLevel': 'ERROR'
        - 'methodSettings."*/*".loggingLevel': 'absent'
  actions:
     - type: update
       patch:
         [ {op: 'replace',
           path: '/*/*/logging/dataTrace',
           value: 'true'},
           {'op': 'replace',
            'path': '/*/*/logging/loglevel',
            'value': 'info'}]


ERROR LOG FROM LAMBDA BELOW:

START RequestId: f03219f0-0204-11e8-bfa2-375a73da4b88 Version: $LATEST
[INFO]	2018-01-25T19:05:38.27Z	ba698e66-0202-11e8-aa75-f7307bfa0f98	Processing event
{
    "account": "xxxxxxxxxxxxx",
    "region": "us-east-1",
    "detail": {
        "eventVersion": "1.05",
        "eventID": "a225ceba-359e-4485-a625-xxxxxxxxxxxx",
        "eventTime": "2018-01-25T19:05:15Z",
        "requestParameters": {
            "restApiId": "eq0jddyumi",
            "template": false,
            "createDeploymentInput": {
                "stageDescription": "jambo2",
                "description": "jambo2",
                "stageName": "jambo2"
            }
        },
        "eventType": "AwsApiCall",
        "responseElements": {
            "description": "jambo2",
            "self": {
                "deploymentId": "yts7jq",
                "restApiId": "eq0jddyumi",
                "template": false
            },
            "deploymentDelete": {
                "deploymentId": "yts7jq",
                "restApiId": "eq0jddyumi",
                "template": false
            },
            "deploymentStages": {
                "deploymentId": "yts7jq",
                "restApiId": "eq0jddyumi",
                "template": false,
                "templateSkipList": [
                    "position"
                ]
            },
            "deploymentUpdate": {
                "deploymentId": "yts7jq",
                "restApiId": "eq0jddyumi",
                "template": false
            },
            "createdDate": "Jan 25, 2018 7:05:14 PM",
            "id": "yts7jq"
        },
        "awsRegion": "us-east-1",
        "eventName": "CreateDeployment",
        "readOnly": false,
        "userIdentity": {
            "principalId": "ROLEIDWASHERE:MyLANIDWASHERE",
            "accessKeyId": "ASIAI2ZZJGACCESSKEY",
            "sessionContext": {
                "sessionIssuer": {
                    "userName": "ROLENAMEWASHERE",
                    "type": "Role",
                    "arn": "arn:aws:iam::xxxxxxxxxxxxx:role/ROLENAMEWASHERE",
                    "principalId": "ROLEIDWASHERE",
                    "accountId": "xxxxxxxxxxxxx"
                },
                "attributes": {
                    "creationDate": "2018-01-25T16:18:21Z",
                    "mfaAuthenticated": "false"
                }
            },
            "type": "AssumedRole",
            "arn": "arn:aws:sts::xxxxxxxxxxxxx:assumed-role/ROLENAMEWASHERE/MyLANIDWASHERE",
            "accountId": "xxxxxxxxxxxxx"
        },
        "eventSource": "apigateway.amazonaws.com",
        "requestID": "ace83816-0202-11e8-8981-af0d569a6a33",
        "userAgent": "Apache-HttpClient/4.5.x (Java/1.8.0_144)",
        "sourceIPAddress": "MY IP ADDRESS"
    },
    "detail-type": "AWS API Call via CloudTrail",
    "source": "aws.apigateway",
    "version": "0",
    "time": "2018-01-25T19:05:15Z",
    "debug": true,
    "id": "fa844ff9-3f67-3cf3-6e1f-ddddddddddd",
    "resources": []
}
[DEBUG]	2018-01-25T19:21:27.974Z	f03219f0-0204-11e8-bfa2-375a73da4b88	Disabling cache
[INFO]	2018-01-25T19:21:27.974Z	f03219f0-0204-11e8-bfa2-375a73da4b88	Found resource ids: [u'eq0jddyumi']
type object 'resource_type' has no attribute 'filter_name': AttributeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 109, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 712, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 436, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 413, in resolve_resources
resources = self.policy.resource_manager.get_resources(resource_ids)
File "/var/task/c7n/query.py", line 421, in get_resources
resources = self.augment(self.source.get_resources(ids))
File "/var/task/c7n/query.py", line 210, in get_resources
return self.query.get(self.manager, ids)
File "/var/task/c7n/query.py", line 91, in get
if m.filter_name:
AttributeError: type object 'resource_type' has no attribute 'filter_name'
END RequestId: f03219f0-0204-11e8-bfa2-375a73da4b88
```

**Comment by jtroberts83** [comment]
So went into the apigw.py code and added the filter_name: None to the rest-stage and now it gets farther but now I am getting this error:
```
START RequestId: f58f7fef-0233-11e8-944a-d95e9639d5e2 Version: $LATEST
[INFO]	2018-01-26T01:01:24.907Z	f58f7fef-0233-11e8-944a-d95e9639d5e2	Processing event { "account": "XXXXXXXXXXX", "region": "us-east-1", "detail": { "eventVersion": "1.05", "eventID": "aecc6e12-3370-422d-ae36-24856a1b9a4e", "eventTime": "2018-01-26T00:57:38Z", "requestParameters": { "restApiId": "k3cgxm2jl5", "template": false, "createDeploymentInpu
[DEBUG]	2018-01-26T01:01:25.590Z	f58f7fef-0233-11e8-944a-d95e9639d5e2	Disabling cache
[INFO]	2018-01-26T01:01:25.602Z	f58f7fef-0233-11e8-944a-d95e9639d5e2	Found resource ids: [u'k3cgxm2jl5']
[DEBUG]	2018-01-26T01:01:25.846Z	f58f7fef-0233-11e8-944a-d95e9639d5e2	Disabling cache
[DEBUG]	2018-01-26T01:01:25.962Z	f58f7fef-0233-11e8-944a-d95e9639d5e2	Filtered from 7 to 7 restapi
tuple indices must be integers, not unicode: TypeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 109, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 712, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 436, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 413, in resolve_resources
resources = self.policy.resource_manager.get_resources(resource_ids)
File "/var/task/c7n/query.py", line 421, in get_resources
resources = self.augment(self.source.get_resources(ids))
File "/var/task/c7n/query.py", line 210, in get_resources
return self.query.get(self.manager, ids)
File "/var/task/c7n/query.py", line 107, in get
resources = [r for r in resources if r[m.id] in identities]
TypeError: tuple indices must be integers, not unicode
END RequestId: f58f7fef-0233-11e8-944a-d95e9639d5e2
REPORT RequestId: f58f7fef-0233-11e8-944a-d95e9639d5e2	Duration: 1415.82 ms	Billed Duration: 1500 ms Memory Size: 512 MB	Max Memory Used: 50 MB
```

**Comment by jtroberts83** [comment]
@kapilt 
Notice that in the above lambda error after I added the filter_name: None it now shows 
```
Filtered from 7 to 7 restapi
```
But it should only show 1 rest api as this was triggered via an API CreateDeployment event trigger.  Thoughts?

**Comment by kapilt** [comment]
yeah, there's two pending items on trunk before a release, wrt to lambda policy support on ecs and api gateway.

**Comment by jtroberts83** [comment]
Thanks @kapilt ! 👍

**Comment by kapilt** [comment]
we're going to need to add an additional parent-id selector in the policy for this to work, probably should also have child resources default to saying lambda policies aren't supported during validation, unless its explicitly been coded its unlikely it will work ootb.

**Comment by kapilt** [comment]
for now i'm just going to fail trail policies on child resources during validation. there's a bit too much work to do to enable this for it to be a release blocker, the lambda no-op delta update fixes are important to get out soon.
