### ISSUE TITLE
c7n-org doesn't recognize `mode` in policies

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#2014]
Config file:
```
  - account_id: 'XXXXXXXXXX'
  name: sandbox 
  regions:
  - us-west-2
  role: arn:aws:iam::XXXXXXXXXX:role/myrole
  tags:
  - environment:'non-production'
```
Policy file:
```
policies:
- name: vpc-test
  resource: ec2
  mode:
    type: config-rule
    role: arn:aws:iam::XXXXXXXX:role/cloud-custodian
    timeout: 180
    security_groups: [sg-ea399290]
    subnets: [subnet-3c3d8367,subnet-a09275c6,subnet-278bb56e]
  filters:
    - or: *missing-tag-filters
  actions:
    - type: terminate
      force: true
```
Command execution ouput:
```
c7n-org run -c config/accounts.yml -a sandbox -s logs -u sandbox
2018-02-13 19:51:30,155: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 507, in provision
    role=self.policy.options.assume_role)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 275, in publish
    func, role, s3_uri, qualifier=alias)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 431, in _create_or_update
    params = func.get_config()
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 582, in get_config
    if self.subnets and self.security_groups:
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 714, in subnets
    return self.policy.data[mode].get(subnets, None)
NameError: global name 'mode' is not defined
2018-02-13 19:51:30,673: c7n_org:ERROR Exception running policy:config_ec2_terminate-invalid-tags account:sandbox region:us-west-2 error:global name 'mode' is not defined
2018-02-13 19:51:30,712: c7n_org:INFO Policy resource counts Counter()
```

**Comment by kapilt** [comment]
i think this is more specific to the config rule then the c7n-org aspect

**Comment by aardvarq** [comment]
Here's what a full `--debug -v` looks like:
```
$ (for i in $(/bin/ls policies/${account}/lambda/*.yml); do c7n-org run -v --debug -c config/accounts.yml -a ${account} -r us-west-2 -s /tmp/foo -u ${i}; done)
2018-02-13 23:10:28,925: c7n_org:DEBUG Running policy:config_ec2_terminate-invalid-tags account:sandbox region:us-west-2
2018-02-13 23:10:30,007: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 507, in provision
    role=self.policy.options.assume_role)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 275, in publish
    func, role, s3_uri, qualifier=alias)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 401, in _create_or_update
    new_config = func.get_config()
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 582, in get_config
    if self.subnets and self.security_groups:
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 714, in subnets
    return self.policy.data[mode].get(subnets, None)
NameError: global name 'mode' is not defined
2018-02-13 23:10:30,008: c7n_org:ERROR Exception running policy:config_ec2_terminate-invalid-tags account:sandbox region:us-west-2 error:global name 'mode' is not defined
> /usr/local/lib/python2.7/site-packages/c7n/mu.py(714)subnets()
-> return self.policy.data[mode].get(subnets, None)
(Pdb) 
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/c7n_org/cli.py", line 387, in run
    debug)] = (a, r)
  File "/usr/local/lib/python2.7/site-packages/c7n/executor.py", line 63, in submit
    return MainThreadFuture(func(*args, **kw))
  File "/usr/local/lib/python2.7/site-packages/c7n_org/cli.py", line 339, in run_account
    resources = p.run()
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 748, in __call__
    resources = mode.provision()
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 507, in provision
    role=self.policy.options.assume_role)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 275, in publish
    func, role, s3_uri, qualifier=alias)
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 401, in _create_or_update
    new_config = func.get_config()
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 582, in get_config
    if self.subnets and self.security_groups:
  File "/usr/local/lib/python2.7/site-packages/c7n/mu.py", line 714, in subnets
    return self.policy.data[mode].get(subnets, None)
NameError: global name 'mode' is not defined
ERROR: Job failed: exit code 1

```

**Comment by kapilt** [comment]
is this against a release or trunk? on trunk the code doesn't correspond, and it looks fine.

**Comment by kapilt** [comment]
@aardvarq fwiw, 0.8.28.0 was released yesterday, if the issue persists just comment here.

**Comment by aardvarq** [comment]
Sorry for the late response, Kapil - I've been out of pocket. This is resolved now, thank you kindly.
