### ISSUE TITLE
After ugrading to 0.8.28 existing policies are failing

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2020]
Error

```
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/c7n/cli.py", line 398, in main
    command(options)
  File "/usr/local/lib/python2.7/site-packages/c7n/commands.py", line 56, in _load_policies
    collection = policy_load(options, fp, vars=vars)
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 75, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy rds-unused-reminder 
 'aws.rds' is not one of [u'aws.rds-snapshot', u'rds-snapshot']

Failed validating u'enum' in schema[106][u'allOf'][1][u'properties'][u'resource']:
    {u'enum': [u'aws.rds-snapshot', u'rds-snapshot']}

On instance[u'resource']:
    'aws.rds'
```

The same policy works fine after downgrading to 0.8.27.3

**Comment by kapilt** [comment]
do you have the actual policy?

**Comment by kapilt** [comment]
```
$ cat rds.yml
policies:
  - name: old-db
    resource: rds
    filters:
      - type: marked-for-op
        tag: "rds_unused_mark"
        op: notify
      - and:
        - type: value
          value_type: age
          key: InstanceCreateTime
          value: 21
          op: gt
        - type: metrics
          name: DatabaseConnections
          days: 14
          value: 0
          op: equal

(custodian) realms-scythe:custodian kapilt$ custodian validate -c rds.yml
custodia2018-02-15 08:24:14,596: custodian.commands:INFO Configuration valid: rds.yml

(custodian) realms-scythe:custodian kapilt$ custodian version
0.8.28.0
```

not seeing the issue

**Comment by kumarsiyer** [comment]
Worked after doing a fresh install. Closing the issue
