### ISSUE TITLE
IAM-user resource throwing error when using Python3

### ISSUE THREAD

**Issue by teo-scout24** [capitalone/cloud-custodian#2023]
2018-02-15 14:50:01,153 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 306, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 417, in resources
    return self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 90, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/resources/iam.py", line 760, in process
    report = self.get_credential_report()
  File "/var/task/c7n/resources/iam.py", line 680, in get_credential_report
    headers = next(reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
2018-02-15 14:50:01,157 - custodian.commands - ERROR - Error while executing policy iam-user, continuing
Traceback (most recent call last):
  File "/var/task/c7n/commands.py", line 217, in run
    policy()
  File "/var/task/c7n/policy.py", line 783, in __call__
    resources = PullMode(self).run()
  File "/var/task/c7n/policy.py", line 306, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 417, in resources
    return self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 90, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/resources/iam.py", line 760, in process
    report = self.get_credential_report()
  File "/var/task/c7n/resources/iam.py", line 680, in get_credential_report
    headers = next(reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

**Comment by kapilt** [comment]
thanks fro the pr, closing.
