### ISSUE TITLE
key error on deleting ebs snapshots

### ISSUE THREAD

**Issue by jeffastorey** [capitalone/cloud-custodian#204]
This error can occur when deleting ebs snapshots

```
ERROR - custodian.output - Error while executing policy Traceback (most recent call last):
File "/usr/local/custodian/lib/python2.7/site-packages/c7n/policy.py", line 207, in poll results = a.process(resources)
File "/usr/local/custodian/lib/python2.7/site-packages/c7n/resources/ebs.py", line 70, in process snaps.add(dev['Ebs']['SnapshotId'])
KeyError: 'SnapshotId'`
```

I believe this is happening when there are non-EBS backed AMIs and a check needs to be made for the presence of the `SnapshotId` key

**Comment by ewbankkit** [comment]
I can take a look at this.

**Comment by ewbankkit** [comment]
Here's an example of an **Image** that causes the problem:
```json
{
    "Architecture": "x86_64",
    "BlockDeviceMappings": [
        {
            "DeviceName": "/dev/sda1",
            "Ebs": {
                "DeleteOnTermination": true,
                "Encrypted": false,
                "SnapshotId": "snap-12345678",
                "VolumeSize": 20,
                "VolumeType": "gp2"
            }
        },
        {
            "DeviceName": "/dev/sdb",
            "Ebs": {
                "DeleteOnTermination": true,
                "Encrypted": true,
                "VolumeSize": 20,
                "VolumeType": "gp2"
            }
        },
        {
            "DeviceName": "/dev/sdc",
            "Ebs": {
                "DeleteOnTermination": true,
                "Encrypted": true,
                "VolumeSize": 200,
                "VolumeType": "gp2"
            }
        }
    ],
    "CreationDate": "2016-05-04T15:38:50.000Z",
    "Description": "Blah blah blah",
    "Hypervisor": "xen",
    "ImageId": "ami-12345678",
    "ImageType": "machine",
    "Public": false,
    "RootDeviceName": "/dev/sda1",
    "RootDeviceType": "ebs",
    "SriovNetSupport": "simple",
    "State": "available",
    "VirtualizationType": "hvm"
}
```

**Comment by kapilt** [comment]
doh, yeah the ami was setup to create a new block dev, we handled this in the other ami block devs scans, probably something to consolidate handling on, thanks again.
