### ISSUE TITLE
(UnsupportedOperation) when calling the ModifyInstanceAttribute operation: Modifying 'disableApiTermination' is not supported for spot instances

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#2083]
When a terminate action has "force:true" attribute attempts to take action on an ec2 spot instance, the following error is received.  CloudCustodian should be modified to only attempt to call ModifyInstanceAttribute if disableApiTermination=true for the instance it should terminate.

 An error occurred (UnsupportedOperation) when calling the ModifyInstanceAttribute operation: Modifying 'disableApiTermination' is not supported for spot instances.: ClientError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 109, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 712, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 470, in run
results = action.process(resources)
File "/var/task/c7n/resources/ec2.py", line 1049, in process
self.disable_deletion_protection(instances)
File "/var/task/c7n/resources/ec2.py", line 1076, in disable_deletion_protection
list(w.map(process_instance, instances))
File "/var/runtime/concurrent/futures/_base.py", line 641, in result_iterator
yield fs.pop().result()
File "/var/runtime/concurrent/futures/_base.py", line 462, in result
return self.__get_result()
File "/var/runtime/concurrent/futures/thread.py", line 63, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/c7n/utils.py", line 410, in _f
return f(*args, **kw)
File "/var/task/c7n/resources/ec2.py", line 1069, in process_instance
Value='false')
File "/var/task/c7n/utils.py", line 348, in _retry
return func(*args, **kw)
File "/var/runtime/botocore/client.py", line 317, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 615, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (UnsupportedOperation) when calling the ModifyInstanceAttribute operation: Modifying 'disableApiTermination' is not supported for spot instances.

**Comment by kapilt** [comment]
the issue is partly that determining if disable api termination is enabled that requires another api call per resource. we could probably just detect that its a spot instance and not bother to modify it on force
