### ISSUE TITLE
Error while running report command for vpc-endpoint resource

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2133]
#### Policy 

> policies:
> 
>   - name: vpc-endpoint
>     resource: vpc-endpoint

```
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 9, in <module>
    load_entry_point('c7n-org==0.2.2', 'console_scripts', 'c7n-org')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 242, in report
    fields=prefix_fields)
  File "/usr/local/lib/python2.7/dist-packages/c7n/reports/csvout.py", line 158, in __init__
    if model.name != model.id:
AttributeError: type object 'resource_type' has no attribute 'name'```

**Comment by kapilt** [comment]
noted, thanks for the bug report.
