### ISSUE TITLE
Error running c7n-org version 0.3.1

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2168]
```
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 9, in <module>
    load_entry_point('c7n-org==0.3.1', 'console_scripts', 'c7n-org')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 459, in run
    for p, count in f.result().items():
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
KeyError: 'profile'```

**Comment by thisisshi** [comment]
What command did you use?

**Comment by kumarsiyer** [comment]
This is an issue with gracefully handling the role/profile not found scenario. I did some debugging and found that when a role or profile is not found c7n-org is just exiting instead of handling the error.

**Comment by kapilt** [comment]
yeah.. looks like issue from adding profile support, i'll take a look.

**Comment by kapilt** [comment]
thats odd, i've run a few policies through org and i'm looking at the config files, i don't have profile defined.

what actual command are you running?

**Comment by kumarsiyer** [comment]
INFO:export-config-gen:role not found `account-name`
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 9, in <module>
    load_entry_point('c7n-org==0.3.1', 'console_scripts', 'c7n-org')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 448, in run
    debug)] = (a, r)
  File "/usr/local/lib/python2.7/dist-packages/c7n/executor.py", line 63, in submit
    return MainThreadFuture(func(*args, **kw))
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 374, in run_account
    elif account['profile']:
KeyError: 'profile'

**Comment by kapilt** [comment]
validated with @kumarsiyer the underlying issue was using an empty string for role and not specifying profile. i've got a pr that will tighten the validation up to flag that as a validation error.

**Comment by kumarsiyer** [comment]
Thanks @kapilt 👍
