### ISSUE TITLE
EC2 Snapshot error when existing 'Name' tag is present

### ISSUE THREAD

**Issue by LykinsN** [capitalone/cloud-custodian#2301]
With the EC2 snapshot refactor, there will be a duplicate tag error if the instance being used to create a snapshot already has a tag present called `Name`. A new `Name` tag is generated from the VolumeID for use on the snapshot,  and this causes a collision with the existing `Name` tag on the instance. 

https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/ec2.py#L1144

This seems like a potential issue with any other existing tags that overlap with the new ones generated in get_snapshot_tags().

```
Traceback (most recent call last):
  File "***/cloud-custodian/cloud-custodian/c7n/commands.py", line 227, in run
    policy()
  File "***/cloud-custodian/cloud-custodian/c7n/policy.py", line 707, in __call__
    resources = mode.run()
  File "***/cloud-custodian/cloud-custodian/c7n/policy.py", line 254, in run
    results = a.process(resources)
  File "***/cloud-custodian/cloud-custodian/c7n/resources/ec2.py", line 1111, in process
    raise f.exception()
ClientError: An error occurred (InvalidParameterValue) when calling the CreateSnapshot operation: Duplicate tag key 'Name' specified.

One possible workaround is to rename the new tag set being generated to something less generic, such as `Snapshot_Name`, or something similar, though this will still lead to a potential naming conflict.

Thoughts?

**Comment by kapilt** [comment]
we should probably just override the name if its already given, ie. use a mapping/dict instead of a list and ensure correct ordering to population (last one wins), and then gen the list in tag value specification before we do the api call.

**Comment by kapilt** [comment]
This feels like a policy error, their explicitly configuring copy-tags on Name, they'll lose the metadata on the ebs volume id if they do so. I'll do some work to support it (ie. no traceback) but not sure if it should be done. I'll try and capture the VolumeId to a separate tag i guess, we'll need for more advanced backup policy management (schedule keep 1 weekly, 3 monthly, etc).
