### ISSUE TITLE
Bug: Elasticache Snapshot `copy-cluster-tags` action errors out if source cluster has more than 1 node

### ISSUE THREAD

**Issue by salwandhruvdev** [capitalone/cloud-custodian#2327]
Elasticache Snapshots `describe_snapshots` response doesn't contain `CacheClusterId ` if the source cluster has more than one node, so `copy-cluster-tags` errors out [here](https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/elasticache.py#L445).

**Comment by kapilt** [comment]
traceback?

**Comment by salwandhruvdev** [comment]
```
Traceback (most recent call last):
File "c7n/commands.py", line 237, in run
policy()
File "c7n/policy.py", line 707, in __call__
resources = mode.run()
File "c7n/policy.py", line 254, in run
results = a.process(resources)
File "c7n/resources/elasticache.py", line 445, in process
if s['CacheClusterId'] not in clusters:
KeyError: u'CacheClusterId'
```
