### ISSUE TITLE
py3 custodian sans subcommands raises error

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#2332]
This appears to have been regress for a while

```
 $ custodian
Traceback (most recent call last):
  File "/Users/kapil/projects/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/kapil/projects/cloud-custodian/c7n/cli.py", line 335, in main
    _setup_logger(options)
  File "/Users/kapil/projects/cloud-custodian/c7n/cli.py", line 301, in _setup_logger
    level = 3 + (options.verbose or 0) - (options.quiet or 0)
AttributeError: 'Namespace' object has no attribute 'verbose'
```

expected output

```
$ custodian 
usage: custodian [-h] {report,logs,metrics,version,validate,schema,run} ...

Cloud fleet management

positional arguments:
  {report,logs,metrics,version,validate,schema,run}
    report              Report of resources that a policy matched/ran on. The
                        default output format is csv, but other formats are
                        available.
    logs                Get policy execution logs from s3 or cloud watch logs
    metrics             Retrieve metrics for policies from CloudWatch Metrics
    version             Display installed version of custodian
    validate            Validate config files against the json schema
    schema              Interactive cli docs for policy authors
    run                 Execute the policies in a config file Multiple regions
                        can be passed in, as can the symbolic region 'all'.
                        When running across multiple regions, policies
                        targeting resources in regions where they do not exist
                        will not be run. The output directory when passing
                        multiple regions is suffixed with the region.
                        Resources with global endpoints are run just once and
                        are suffixed with the first region passed in or us-
                        east-1 if running against 'all' regions.

optional arguments:
  -h, --help            show this help message and exit
```

**Comment by kapilt** [comment]
there's some variance here between python2 and python3, so its not per se a regression, just a compatibility issue, python2 does currently do a short form message like this

```
$ custodian
usage: custodian [-h] {report,logs,metrics,version,validate,schema,run} ...
custodian: error: too few arguments
```

where as python3 gives that traceback above.
