### ISSUE TITLE
c7n-mailer slack messages

### ISSUE THREAD

**Issue by jaxxstorm** [capitalone/cloud-custodian#2366]
I'm trying to send a slack message using the mailer.

My `mailer.yaml`

```
queue_url: https://sqs.us-west-2.amazonaws.com/<account_id>/lbriggs-test
role: arn:aws:iam::<account_id>:user/lbriggs
slack_token: <token>
region: us-west-2
```

When running with debug:

```
2018-05-09 08:51:34,599 - botocore.client - DEBUG - Registering retry handlers for service: sts
2018-05-09 08:51:34,602 - custodian-mailer - DEBUG - Found no sns addresses, delivering no messages.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable region from instance vars with value 'us-west-2'.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-09 08:51:34,617 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,617 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1040f9140>
2018-05-09 08:51:34,618 - botocore.loaders - DEBUG - Loading JSON file: /Users/Lee/.local/share/virtualenvs/cloud-custodian-QbyRcG0f/lib/python2.7/site-packages/botocore/data/kms/2014-11-01/service-2.json
2018-05-09 08:51:34,630 - botocore.hooks - DEBUG - Event creating-client-class.kms: calling handler <function add_generate_presigned_url at 0x1040b3848>
2018-05-09 08:51:34,630 - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-05-09 08:51:34,632 - botocore.endpoint - DEBUG - Setting kms timeout as (60, 60)
2018-05-09 08:51:34,633 - botocore.client - DEBUG - Registering retry handlers for service: kms
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file utils.py, line 300
2018-05-09 08:51:34,634 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,634 - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-05-09 08:51:34,635 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,635 - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-09 08:51:34,635 - botocore.session - DEBUG - Loading variable profile from environment with value 'engineering'.
2018-05-09 08:51:34,635 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1040f9140>
2018-05-09 08:51:34,636 - botocore.hooks - DEBUG - Event creating-client-class.ses: calling handler <function add_generate_presigned_url at 0x1040b3848>
2018-05-09 08:51:34,636 - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-05-09 08:51:34,638 - botocore.endpoint - DEBUG - Setting email timeout as (60, 60)
2018-05-09 08:51:34,639 - botocore.client - DEBUG - Registering retry handlers for service: ses
2018-05-09 08:51:34,639 - custodian-mailer - DEBUG - Slack payload, skipping email.
2018-05-09 08:51:34,639 - custodian-mailer - DEBUG - Found no email addresses, sending no emails.
Traceback (most recent call last):
  File "/Users/Lee/.local/share/virtualenvs/cloud-custodian-QbyRcG0f/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/Users/Lee/github/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 145, in main
    MailerSqsQueueProcessor(mailer_config, aws_session, logger).run()
  File "/Users/Lee/github/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 126, in run
    self.process_sqs_message(sqs_message)
  File "/Users/Lee/github/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 172, in process_sqs_message
    slack_messages = slack_delivery.get_to_addrs_slack_messages_map(sqs_message)
  File "/Users/Lee/github/cloud-custodian/tools/c7n_mailer/c7n_mailer/slack_delivery.py", line 76, in get_to_addrs_slack_messages_map
    to_addrs_to_resources_map.values()[0],
IndexError: list index out of range
```

**Comment by LykinsN** [comment]
I've pushed a fix that should resolve this issue. It's currently checked in under a development branch. Can you try running against the branch and verify this resolves the problem?

https://github.com/LykinsN/cloud-custodian/tree/mailer-fix

**Comment by jaxxstorm** [comment]
This didn't seem to help much but I could be doing something wrong

**Comment by LykinsN** [comment]
Can you try this branch? I reverted some other dependency changes there. If you're still having issues, I'll reach out to you directly. 

https://github.com/LykinsN/cloud-custodian/tree/mailer-test

**Comment by LykinsN** [comment]
Also, if you still have issues, can you provide the latest traceback?
