### ISSUE TITLE
c7n_mailer's slack_delivery for specific users only works on Enterprise Grid

### ISSUE THREAD

**Issue by mateusz** [capitalone/cloud-custodian#2409]
I'm getting `KeyError: 'enterprise_user'` in `c7n_mailer/slack_delivery.py` with `slack://joe@cow.org` on master.

This here https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_mailer/c7n_mailer/slack_delivery.py#L142 checks for 'enterprise_user', which will only work for Slack Enterprise Grid™️ users - see [https://api.slack.com/types/user](https://api.slack.com/types/user).

"Normal" slack accounts seem to have their id under ['user']['id'].

```
Traceback (most recent call last):
  File "/Users/mateusz/Sites/cloud-custodian/c7n_mailer/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/Users/mateusz/Sites/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 146, in main
    MailerSqsQueueProcessor(mailer_config, aws_session, logger).run()
  File "/Users/mateusz/Sites/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 126, in run
    self.process_sqs_message(sqs_message)
  File "/Users/mateusz/Sites/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 172, in process_sqs_message
    slack_messages = slack_delivery.get_to_addrs_slack_messages_map(sqs_message)
  File "/Users/mateusz/Sites/cloud-custodian/tools/c7n_mailer/c7n_mailer/slack_delivery.py", line 79, in get_to_addrs_slack_messages_map
    resolved_addrs = self.retrieve_user_im([target.split('slack://', 1)[1]])
  File "/Users/mateusz/Sites/cloud-custodian/tools/c7n_mailer/c7n_mailer/slack_delivery.py", line 143, in retrieve_user_im
    response['user']['enterprise_user']['id'])
```

**Comment by LykinsN** [comment]
Fixed in https://github.com/capitalone/cloud-custodian/pull/2431

**Comment by LykinsN** [comment]
Can you confirm that this change corrected the issue?

**Comment by dimamedvedev** [comment]
Fixed in https://github.com/capitalone/cloud-custodian/pull/2452
