### ISSUE TITLE
salactus tuple index out of range error when inspecting queue on pending items if no bucket is passed in

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#2422]
```
$ c7n-salactus inspect-queue --queue buckets-iterator --state pending
Traceback (most recent call last):
  File "/home/llq270/cloud-custodian/bin/c7n-salactus", line 11, in <module>
    load_entry_point('c7n-salactus', 'console_scripts', 'c7n-salactus')()
  File "/home/llq270/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/llq270/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/llq270/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/llq270/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/llq270/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/llq270/cloud-custodian/tools/c7n_salactus/c7n_salactus/cli.py", line 734, in inspect_queue
    records.append(job_row(j))
  File "/home/llq270/cloud-custodian/tools/c7n_salactus/c7n_salactus/cli.py", line 696, in job_row
    account, bucket = j.args[0]['name'], "set %d" % len(j.args[1])
IndexError: tuple index out of range
```

printing out `j.args`, I get:

```python
(
  {'account-id': 'XXXXXXXXXXXX', 
  'canonical-id': 'XXXXXXXXXXX', 
  'name': 'XXXXXXXXXXX', 
  'tags': ['dev', 'division:XXXXXXXXXXX'], 
  'regions': ['us-east-1', 'eu-west-1'], 
  'visitors': [{'type': 'encrypt-keys'}], 
  'role': 'arn:aws:iam::XXXXXXXXXXXX:role/XXXXXXXXXXX', 
  'inventory': {
    'bucket-size-threshold': 0, 
    'id-selector': 'salactus'
    }
  },
)
```

**Comment by kapilt** [comment]
both this and #2423 seem to be due to a dependency upgrade that changed some semantics (I'd suspect rq), we might need to pin this to previous version.
