### ISSUE TITLE
c7n-salactus raises type error when inspecting queue and filtering on 'failed' state

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#2423]
```
$ c7n-salactus inspect-queue --queue buckets-iterator --state failed
Traceback (most recent call last):
  File "/home/xxxxxx/cloud-custodian/bin/c7n-salactus", line 11, in <module>
    load_entry_point('c7n-salactus', 'console_scripts', 'c7n-salactus')()
  File "/home/xxxxxx/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxxxxx/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xxxxxx/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxxxxx/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxxxxx/cloud-custodian/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xxxxxx/cloud-custodian/tools/c7n_salactus/c7n_salactus/cli.py", line 728, in inspect_queue
    registry = registry_class(queue, connection=conn)
TypeError: __init__() got multiple values for keyword argument 'connection'
```

**Comment by kapilt** [comment]
could you report pip freeze output, that seems like a regression from a dependency upgrade

**Comment by thisisshi** [comment]
```
$ pip freeze
```

https://gist.github.com/thisisshi/d41d31561070da2951fa85f02b58b7cf
