### ISSUE TITLE
Ability to disable AWS console access for iam-user 

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2450]
Is there a way to disable console access for IAM users?

The use cases are as follows:

**Use Case 1**
Company A has contractors who have been hired for a period of time.
Upon completion of work, the employer would like the contractor IAM user accounts' (1) access keys removed and (2) access to the management console disabled.  As the contractors may be brought on to perform future work, there is no need to delete the accounts.

**Use Case 2**
Company A performs periodic audits of IAM users in the admin group. Any IAM users that do not have MFA enabled per corporate security policies will have their access-keys removed and access to the management console disabled.

The iam-user schema satisfies the first business requirement of access key deletion (via remove-keys). 
And we can run this against a cron job which fits perfectly.

However, I don't see an action to disable IAM user console access. 

It appears we'd have to perform this task manually?

**Comment by davidclin** [comment]
That would indeed make the policy more flexible and readable at the same time. 👍

**Comment by thisisshi** [comment]
@kapilt what do you think of the approach here?

**Comment by thisisshi** [comment]
@davidclin https://github.com/capitalone/cloud-custodian/pull/2454 here's a PR regarding the change, let me know if you have any feedback

**Comment by davidclin** [comment]
How do I get my hands on the latest branch along with a working example? I'm more than happy to test it out and provide user feedback. :)

**Comment by thisisshi** [comment]
you can clone my fork and run it:

```shell
$ git clone https://www.github.com/thisisshi/cloud-custodian
$ cd cloud-custodian
$ git checkout iam-user-delete-extend
$ make install
$ source bin/activate
(cloud-custodian) $ custodian run ...
```

**Comment by davidclin** [comment]
Ran into some issues:

(1) `ImportError: No module named oath2client` message coming from c7n_gcp/client.py:

```
(cloud-custodian) [ec2-user@ip-10-100-0-65 cloudcustodian]$ custodian run -s output --dryrun foo.yml
2018-06-01 22:52:29,012: keyring.backend:INFO Loading SecretService
2018-06-01 22:52:29,014: keyring.backend:INFO Loading kwallet
2018-06-01 22:52:29,015: keyring.backend:INFO Loading macOS
2018-06-01 22:52:29,017: keyring.backend:INFO Loading windows
Traceback (most recent call last):
  File "/home/ec2-user/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/home/ec2-user/cloud-custodian/c7n/cli.py", line 357, in main
    command(config)
  File "/home/ec2-user/cloud-custodian/c7n/commands.py", line 55, in _load_policies
    load_resources()
  File "/home/ec2-user/cloud-custodian/c7n/resources/__init__.py", line 94, in load_resources
    resources.load_plugins()
  File "/home/ec2-user/cloud-custodian/c7n/registry.py", line 109, in load_plugins
    f = ep.load()
  File "/home/ec2-user/cloud-custodian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/ec2-user/cloud-custodian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ec2-user/cloud-custodian/tools/c7n_gcp/c7n_gcp/entry.py", line 17, in <module>
    import c7n_gcp.resources.resourcemanager
  File "/home/ec2-user/cloud-custodian/tools/c7n_gcp/c7n_gcp/resources/resourcemanager.py", line 16, in <module>
    from c7n_gcp.provider import resources
  File "/home/ec2-user/cloud-custodian/tools/c7n_gcp/c7n_gcp/provider.py", line 18, in <module>
    from .client import Session
  File "/home/ec2-user/cloud-custodian/tools/c7n_gcp/c7n_gcp/client.py", line 19, in <module>
    from oauth2client import client
ImportError: No module named oauth2client

```
Workaround `$ pip install --upgrade oath2client`

(2) Getting cryptic messages related to SecretService, kwallet, macOS, and windows:

```
(cloud-custodian) $ custodian run -s out --dryrun foo.yml
2018-06-01 23:17:11,890: keyring.backend:INFO Loading SecretService
2018-06-01 23:17:11,891: keyring.backend:INFO Loading kwallet
2018-06-01 23:17:11,891: keyring.backend:INFO Loading macOS
2018-06-01 23:17:11,892: keyring.backend:INFO Loading windows
2018-06-01 23:17:22,845: custodian.policy:INFO policy: mfa-unused-test resource:iam-user region:us-east-1 count:1 time:10.41

```

(3) Created 3 IAM users in group named "CloudCustodianUsers" that do not have MFA enabled and am only seeing **1 count match**. Tried clearing the cache via `rm ~/.cache/cloud-custodian.cache` but noticed no change.

(4) For the match on the one IAM user, none of the options specified in the policy are deleted (i.e. ssh-keys, console-access, and access-keys) when viewed from the management console. 

```
policies:
  - name: mfa-unused-test
    resource: iam-user
    description: |
      Retrieve list of all IAM users in the group 'CloudCustodianAdmins'
      who have not enabled MFA and delete their ssh-keys, access-keys, and access to console
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: CloudCustodianAdmins
    actions:
      - type: delete
        options:
          - ssh-keys
          - console-access
          - access-keys
```

**Comment by thisisshi** [comment]
Are you sure the users had console and access keys? The test that was added in the pr explicitly tested deleting those two. See tests/test_iam.py in the pr for the policy that was tested

**Comment by davidclin** [comment]
My apologies.  User error.  

I was switching between hyperlinks in the IAM console window expecting the user information to refresh when clicking back. For example, I would run the policy, click one the "Roles" or "Groups" link in the left navigation bar in the management console, then navigate back to my IAM users's security credentials tab.  

As soon as I read your email this morning, I realized the information was likely getting cached by Chrome. 

When clicking my browser's refresh page button, sure enough I'm able to see that the IAM users' options are immediately disabled/deleted (in my case, ssh-keys/console-access/access-keys).

Works great!

**Comment by davidclin** [comment]
Coming back to issue (1), will the oath2client come bundled with latest custodian or will users need to install the module?

**Comment by thisisshi** [comment]
You shouldn't need to install oauth2client yourself, I'll look into this. Thanks!
