### ISSUE TITLE
Occasional 'LoadBalancerNotFound' errors when getting ELB tags

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#247]
Occasionally we see `LoadBalancerNotFound` errors when getting ELB tags:
```
2016-06-28 16:05:44,966: custodian.elb:ERROR Exception Processing ELB: An error occurred (LoadBalancerNotFound) when calling the DescribeTags operation: Cannot find Load Balancer XYZ
Traceback (most recent call last):
  File "/src/c7n/resources/elb.py", line 58, in process_tags
    results = client.describe_tags(LoadBalancerNames=elb_map.keys())
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 262, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 552, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (LoadBalancerNotFound) when calling the DescribeTags operation: Cannot find Load Balancer XYZ
2016-06-28 16:05:45,083: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 191, in poll
    resources = self.resource_manager.resources()
  File "/src/c7n/query.py", line 63, in resources
    resources = self.augment(resources)
  File "/src/c7n/resources/elb.py", line 48, in augment
    resources, self.session_factory, self.executor_factory)
  File "/src/c7n/resources/elb.py", line 66, in _elb_tags
    list(w.map(process_tags, chunks(elbs, 20)))
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 581, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/c7n/resources/elb.py", line 58, in process_tags
    results = client.describe_tags(LoadBalancerNames=elb_map.keys())
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 262, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 552, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (LoadBalancerNotFound) when calling the DescribeTags operation: Cannot find Load Balancer XYZ
```
This aborts the policy.
This is probably caused by cache staleness when ELBs are being created and destroyed frequently.
I suggest just ignoring this error.

**Comment by ewbankkit** [comment]
Looks similar to https://github.com/capitalone/cloud-custodian/issues/207.

**Comment by kapilt** [comment]
This is actually pre-cache, augment output is what gets cached.

**Comment by ewbankkit** [comment]
So, what do you think we should do?

**Comment by kapilt** [comment]
catch exception, return None else return elb resource on the inner func, on the outer do return filter(None, w.map(inner_func, resource_list)

**Comment by ewbankkit** [comment]
Hmm. Since the `describe_tags` call is being made in chunks of 20 ELBs and the call fails if any of the ELBs are missing we can't just filter out a single ELB.
I wouldn't like to query each ELB at a time for tags or filter out a whole chunk of 20 ELBs.
Since I've only every seen this error once I am thinking about closing this (and the associated PR) as _Do Not Fix_.

**Comment by kapilt** [comment]
in a few other cases on group ops, we catch not found, parse error for the id strings, remove from set and retry. might be overkill for this case.

**Comment by ewbankkit** [comment]
Yes, I feel it's overkill.
I'm closing this issue (and associated PR).
