### ISSUE TITLE
Issue with #2454 when run as lambda

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2472]
This ticket is related to #2454. 

When policy is run as a **Lambda** function, the following messages appear in the CloudWatch logs:

```
[ERROR]	2018-06-05T22:20:12.415Z	79a5d662-690e-11e8-bd2d-d557592c4236	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 229, in run
resources = self.policy.resource_manager.resources()
File "/var/task/c7n/query.py", line 421, in resources
return self.filter_resources(resources)
File "/var/task/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/iam.py", line 960, in process
for p in r['c7n:Groups']:
KeyError: u'c7n:Groups'
u'c7n:Groups': KeyError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 89, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 739, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 504, in run
return PullMode.run(self)
File "/var/task/c7n/policy.py", line 229, in run
resources = self.policy.resource_manager.resources()
File "/var/task/c7n/query.py", line 421, in resources
return self.filter_resources(resources)
File "/var/task/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/iam.py", line 960, in process
for p in r['c7n:Groups']:
KeyError: u'c7n:Groups'
```

Policy
```
policies:
  - name: mfa-unused-audit
    description: |
      Cloud Custodian MFA Admin Audit
    comments: |
      Retrieve list of all IAM users in the group 'CloudCustodianAdmins'
      who have not enabled MFA and delete their ssh-keys and access-keys.
      Also, disable access to management console.
    resource: iam-user
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodianRole
      schedule: "rate(1 minute)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: CloudCustodianAdmins
    actions:
      - type: delete
        options:
          - access-keys
          - ssh-keys
          - console-access
```

The policy runs clean when run locally.

**Comment by thisisshi** [comment]
Does this issue occur when running from master? I don't think this is related to the additional functionality added in that PR, rather this is an issue related to the group filter

**Comment by davidclin** [comment]
You're right! 

I'm getting the same errors when run from master.

<hr>

**Revised policy without the additional functionaility**
```
policies:
  - name: iam-user-with-lambda
    resource: iam-user
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodianRole
      schedule: "rate(1 minute)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: CloudCustodianAdmins
    actions:
      - type: notify
        template: mfa-unused-disable
        template_format: 'html'
        template_slack: slack-mfa-unused-disable
        priority_header: '5'
        subject: 'Cloud Custodian: IAM User Admins Audit'
        to:
          - email@address.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/sandbox
```
<hr>

**Error Logs**
```
[ERROR]	2018-06-06T00:32:06.152Z	09408266-6921-11e8-b952-9b97ab72eee2	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 222, in run
resources = self.policy.resource_manager.resources()
File "/var/task/c7n/query.py", line 421, in resources
return self.filter_resources(resources)
File "/var/task/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/iam.py", line 947, in process
for p in r['c7n:Groups']:
KeyError: u'c7n:Groups'
u'c7n:Groups': KeyError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 88, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 669, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 468, in run
return PullMode.run(self)
File "/var/task/c7n/policy.py", line 222, in run
resources = self.policy.resource_manager.resources()
File "/var/task/c7n/query.py", line 421, in resources
return self.filter_resources(resources)
File "/var/task/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/iam.py", line 947, in process
for p in r['c7n:Groups']:
KeyError: u'c7n:Groups'
```

**Comment by davidclin** [comment]
I went ahead and changed the title to more accurately reflect the reported issue.

**Comment by kapilt** [comment]
@thisisshi that fix in your commit looks good, wanna send a pr?

**Comment by thisisshi** [comment]
@kapilt it's already in https://github.com/capitalone/cloud-custodian/pull/2454, but I can pull it out if you want it in before the delete options feature instead

**Comment by davidclin** [comment]
While the errors are no longer appearing, my group filter is not matching against any users when run as a Lambda.

Also, when I run my policy locally the group filter only matches when the GroupName is 'Administrators'. 

If the GroupName anything else, the group filter shows no matches.

Temporary workaround is to run policy locally as a cron job -- but ideally, I would like to run it as a Lambda filtering against any custom GroupName given.
