### ISSUE TITLE
Tagging EBS volumes using Cloudtrial

### ISSUE THREAD

**Issue by ngupta7** [capitalone/cloud-custodian#2661]
- name: name-root-volumes
     description: |
       to name all root volumes
     resource: ebs
     mode:
       type: cloudtrail
       role: arn:aws:iam::<account-id>:role/Cloudcustodian
       events:
         - CreateVolume
     filters:
       - tag:onwer: absent
     actions:
       - type: tag
         key: rootvolume
~

This doesnt work when i create a volume manually using console.

**Comment by thisisshi** [comment]
Do you see the lambda executing? can you post the logs from the lambda that was deployed in the account? should be custodian-name-root-volumes

**Comment by ngupta7** [comment]
This is the error i get while executing lambda:

[DEBUG]	2018-07-23T11:50:14.606Z	8f37dddb-8e6e-11e8-8c9c-45a033faef53	Disabling cache
u'detail': KeyError
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 88, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 669, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 379, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 346, in resolve_resources
    resource_ids = CloudWatchEvents.get_ids(event, mode)
  File "/var/task/c7n/cwe.py", line 151, in get_ids
    resource_ids = cls.get_trail_ids(event, mode)
  File "/var/task/c7n/cwe.py", line 118, in get_trail_ids
    event_name = event['detail']['eventName']
KeyError: u'detail'

**Comment by thisisshi** [comment]
are you running this policy manually? any lambda that you're deploying with `mode: cloudtrail` depends on a cloudwatch event that's passed in at the time of execution.

**Comment by thisisshi** [comment]
you can't execute the lambda manually, these lambdas react to cloudtrail events. To test them, you need to execute the api (RunInstances) or create an instance in the console. The reason why you're not finding resource id's is likely because you're passing in a event into the lambda and running it manually, not in response to a cloudwatch event.

Try this:
1. Deploy the custodian policy
2. Go to the console
3. Create a new instance
4. Check the logs
