### ISSUE TITLE
Azure - unable to create or validate policy based on instructions

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#2688]
When following the getting started docs provided for azure, I get the following error. It looks like there's an issue importing the variables set in the actions.py file:

(custodian) ➜  custodian validate custodian.yml
Traceback (most recent call last):
  File "/Users//XXXXXXX/XXX/custodian/bin/custodian", line 11, in <module>
    sys.exit(main())
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/c7n/cli.py", line 362, in main
    command(config)
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/c7n/commands.py", line 165, in validate
    load_resources()
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/c7n/resources/__init__.py", line 93, in load_resources
    resources.load_plugins()
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/c7n/registry.py", line 109, in load_plugins
    f = ep.load()
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/XXXXXXX/XXX/Dev/custodian/lib/python2.7/site-packages/c7n_azure/entry.py", line 16, in <module>
    import c7n_azure.actions
  File "/Users/XXXXXXX/XXX/custodian/lib/python2.7/site-packages/c7n_azure/actions.py", line 22, in <module>
    from c7n.actions import BaseAction, BaseNotify
ImportError: cannot import name BaseNotify

**Comment by kapilt** [comment]
which version of custodian and c7n_azure is that (installed from where ?)

**Comment by jdogg89** [comment]
(custodian) ➜  Dev custodian version
0.8.28.2

$ virtualenv custodian
$ source custodian/bin/activate
(custodian) $ pip install c7n
(custodian) $ pip install c7n_azure

The instructions are on your page here: https://capitalone.github.io/cloud-custodian/docs/azure/gettingstarted.html

**Comment by thisisshi** [comment]
@jdogg89 looks like you're installing custodian via cli, I believe BaseNotify was added recently (not in the pip package version) you fix this by following the developer install found in the docs

**Comment by jdogg89** [comment]
Are these the instructions you're referring to @thisisshi: 
$ git clone https://github.com/capitalone/cloud-custodian.git
$ virtualenv custodian
$ source custodian/bin/activate
(custodian) $ pip install cloud-custodian
(custodian) $ pip install cloud-custodian/tools/c7n_azure

Because when I get to the instructions to install cloud custodian I get an error: (custodian) ➜  Dev pip install cloud-custodian
Collecting cloud-custodian
  Could not find a version that satisfies the requirement cloud-custodian (from versions: )
No matching distribution found for cloud-custodian
(custodian) ➜  Dev python
Python 2.7.14 (default, Mar 22 2018, 15:04:47)

**Comment by thisisshi** [comment]
@jdogg89 these steps here: http://capitalone.github.io/cloud-custodian/docs/developer/installing.html

**Comment by jdogg89** [comment]
There must be a hard dependency on python 3.6, I have 3.7 installed. following the instructions @thisisshi provided I get errors when running tox: 
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:   py37: commands failed

**Comment by thisisshi** [comment]
Yeah, that's because there's a hard coding to 3.6 in the Makefile, I'll look into making it work for any version of py3
