### ISSUE TITLE
c7n-azure version conflict on adal package

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#2695]
getting the following error when running off of master:

```
Traceback (most recent call last):
  File "/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/cloud-custodian/c7n/cli.py", line 357, in main
    command(config)
  File "/cloud-custodian/c7n/commands.py", line 55, in _load_policies
    load_resources()
  File "/cloud-custodian/c7n/resources/__init__.py", line 96, in load_resources
    resources.load_plugins()
  File "/cloud-custodian/c7n/registry.py", line 109, in load_plugins
    f = ep.load()
  File "/cloud-custodian/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2320, in load
    self.require(*args, **kwargs)
  File '/cloud-custodian/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/cloud-custodian/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (adal 0.5.1 (/Users/llq270/dev/cloud-custodian-sonny/cloud-custodian/lib/python3.6/site-packages), Requirement.parse('adal<2.0.0,>=0.6.0'), {'msrestazure'})
```
@stefangordon @aluong

**Comment by ewbankkit** [comment]
It looks like a new version of [`msrestazure`](https://pypi.org/project/msrestazure/) was released today. This may well be the cause of the conflict.

**Comment by thisisshi** [comment]
Yup, @erwelch's PR here: https://github.com/capitalone/cloud-custodian/pull/2696 should fix, there are some test failures on the gcp side as well, looks like the newest gcp python client is causing the failures

**Comment by kapilt** [comment]
merged the azure fix branch, I'll look at the gcp stuff if someone doesn't beat me to it.
