### ISSUE TITLE
c7n: The ec2-instance-state type is missing the event "pending"

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2772]
Did something change recently?

The `ec2-instance-state` type is missing the event "pending".

The following policy was working fine in the past until I tried running it today:

```
policies:
  - name: public-instance-audit
    resource: ec2
    description: |
      Cloud Custodian Public Instance Audit
    mode:
      type: ec2-instance-state
      role: arn:aws:iam::123456789012:role/CloudCustodian
      events:
        - pending
...
```

Traceback
```
(c7n) $ custodian run --dryrun -s output public-instance-audit.yml
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.30.0', 'console_scripts', 'custodian')()
  File "/usr/local/lib/python2.7/dist-packages/c7n/cli.py", line 357, in main
    command(config)
  File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 75, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy public-instance-audit
 {'type': 'ec2-instance-state', 'role': 'arn:aws:iam::929292782238:role/CloudCustodian', 'events': ['pending']} is                  not valid under any of the given schemas

Failed validating u'anyOf' in schema[34][u'allOf'][0][u'properties'][u'mode']:
    {u'anyOf': [{u'additionalProperties': False,
                 u'properties': {u'dead_letter_config': {u'type': u'object'},
                                 u'environment': {u'type': u'object'},
                                 'events': {u'items': {u'enum': [u'running',
                                                                 u'shutting-down',
                                                                 u'stopped',
                                                                 u'stopping',
                                                                 u'terminated']},
                                            u'type': u'array'},
                                 u'execution-options': {u'type': u'object'},
                                 u'function-prefix': {u'type': u'string'},
...
```

This is blocking me as I have admins who use this policy to make changes to the filter to ignore instances based on tag:Name. When the change is committed to GitHub Enterprise, Jenkins kicks off another run and fails because the pending event isn't valid.

**Comment by thisisshi** [comment]
thanks for the bug report, i've opened a pr here: https://github.com/capitalone/cloud-custodian/pull/2777
