### ISSUE TITLE
Azure - Confusing error message if there is schema validation error for azure.vm

### ISSUE THREAD

**Issue by logachev** [capitalone/cloud-custodian#2821]
When there is a schema validation for a policy for azure.vm, the error returns incorrect information for azure.vmss. (Not Azure specific - can repro with AWS RDS resource as well)

Actual:
```
Traceback (most recent call last):
  File "/custodian/src/mount/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/custodian/src/mount/c7n/cli.py", line 357, in main
    command(config)
  File "/custodian/src/mount/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/custodian/src/mount/c7n/policy.py", line 76, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy test
 'azure.vm' is not one of ['azure.vmss']

Failed validating 'enum' in schema[156]['allOf'][1]['properties']['resource']:
    {'enum': ['azure.vmss']}

On instance['resource']:
    'azure.vm'
```

Expected:
```
Traceback (most recent call last):
  File "/custodian/src/mount/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/custodian/src/mount/c7n/cli.py", line 357, in main
    command(config)
  File "/custodian/src/mount/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/custodian/src/mount/c7n/policy.py", line 76, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy test
 'string' is not one of ['age', 'integer', 'expiration', 'normalize', 'size', 'cidr', 'cidr_size', 'swap', 'resource_count', 'expr', 'unique_size']

Failed validating 'enum' in schema[5]['properties']['value_type']:
    {'enum': ['age',
              'integer',
              'expiration',
              'normalize',
              'size',
              'cidr',
              'cidr_size',
              'swap',
              'resource_count',
              'expr',
              'unique_size']}

On instance['value_type']:
    'string'
```

**Comment by kapilt** [comment]
merged
