### ISSUE TITLE
Support for boto core latest version

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2887]
```
custodian version
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (botocore 1.12.4 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('botocore>=1.11.3,<1.12.0'))
```

**Comment by kapilt** [comment]
we do support it, the problem is your boto3 version, if you do pip install -U boto3 does that resolve?

**Comment by kumarsiyer** [comment]
nevermind, that worked.
