### ISSUE TITLE
c7n_org KeyError: 'AccessKeyId'

### ISSUE THREAD

**Issue by davegonzales2004** [capitalone/cloud-custodian#2959]
Hi,

Today I started to receive the below error when running c7n-org, when yesterday this was working. This is weird because I have not made any changes to the IAM roles I'm using. Does anyone have any idea why this broke? I'm currently running "c7n-org-0.4.1":
```
c7n-org run -v --debug -c accounts.yml -s output -u ec2-auto-tag-user.yml --cache-period 0
2018-10-04 18:04:02,813: c7n_org:DEBUG Running policy:ec2-auto-tag-user account:ENG-TEST region:us-east-1
2018-10-04 18:04:02,835: c7n_org:ERROR Exception running policy:ec2-auto-tag-user account:ENG-TEST region:us-east-1 error:'AccessKeyId'
Traceback (most recent call last):
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n_org/cli.py", line 478, in run_account
    resources = p.run()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 868, in __call__
    resources = mode.provision()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 486, in provision
    manager = mu.LambdaManager(self.policy.session_factory)
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/mu.py", line 265, in __init__
    self.client = self.session_factory().client('lambda')
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/credentials.py", line 52, in __call__
    region or self.region, self.external_id)
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/credentials.py", line 99, in assumed_session
    metadata=refresh(),
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/credentials.py", line 90, in refresh
    session.client('sts').assume_role, **parameters)['Credentials']
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/session.py", line 878, in create_client
    credentials = self.get_credentials()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/session.py", line 479, in get_credentials
    'credential_provider').load_credentials()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/credentials.py", line 1663, in load_credentials
    creds = provider.load()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/credentials.py", line 842, in load
    metadata = fetcher.retrieve_iam_role_credentials()
  File "/git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/utils.py", line 321, in retrieve_iam_role_credentials
    'access_key': data[role_name]['AccessKeyId'],
KeyError: 'AccessKeyId'
> /git-repos/cloud-custodian/custodian/lib/python2.7/site-packages/botocore/utils.py(321)retrieve_iam_role_credentials()
-> 'access_key': data[role_name]['AccessKeyId']```

**Comment by kapilt** [comment]
what version of boto is that, that traceback appears to be fairly deep within the botocore stack,

**Comment by davegonzales2004** [comment]
Hi @kapilt 
Looks like I' running:
botocore                     1.10.79

**Comment by davegonzales2004** [comment]
Sorry I was looking at the wrong pip packages. Looks like I'm running:
boto3              1.9.14
botocore           1.12.14

**Comment by davegonzales2004** [comment]
The "KeyError: 'AccessKeyId' message I was getting when running c7n-org, I figured out the issue. For the IAM Role my custodian instance is using, I removed "ec2.amazonaws.com" from the trust relationship. Since this change takes minutes to update, I did not realize this broke c7n-org. 

I add this back and waited a bit for the changes to update and now everything is working.
