### ISSUE TITLE
attach-encrypt should support bucket sns notification

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#297]

**Comment by kapilt** [comment]
First step is adding sns support to mu.py

**Comment by whit537** [comment]
Alright, lessee here ...

**Comment by whit537** [comment]
I find `attach-encrypt` in [code](https://github.com/capitalone/cloud-custodian/blob/22101c4aa5c2c8171324c226fa7e0efe9a519890/c7n/resources/s3.py#L576-L670) but not in [docs](http://www.capitalone.io/cloud-custodian/docs/policy/resources/s3.html#actions).

**Comment by whit537** [comment]
I gather that the purpose of `attach-encrypt` is to install [a Lambda](https://github.com/capitalone/cloud-custodian/blob/22101c4aa5c2c8171324c226fa7e0efe9a519890/c7n/ufuncs/s3crypt.py#L42-L65) (I guess that's the "attach" part?) that [encrypts unencrypted s3 objects](https://github.com/capitalone/cloud-custodian/blob/22101c4aa5c2c8171324c226fa7e0efe9a519890/c7n/resources/s3.py#L957-L1173).

**Comment by whit537** [comment]
@kapilt So what's the tie-in to SNS? Are we publishing to SNS after encrypting? Or are we consuming from SNS as a trigger for encryption? My hunch is the former.

**Comment by ocampocj** [comment]
@whit537 - @kapilt can chime in, in case I'm missing something.  Just as the buckets can trigger lambdas, we want the ability to trigger SNS notifications.  In some edge cases, there are some buckets that already have lambdas attached for other valid reasons.  Since you can't have multiple lambda notifications on a single bucket, we want to trigger SNS instead.  From SNS, multiple lambdas can then be triggered.

**Comment by kapilt** [comment]
consuming from sns, we already have publishing to sns.

**Comment by whit537** [comment]
> First step is adding sns support to mu.py

Starting a PR for this in https://github.com/capitalone/cloud-custodian/pull/869 ...

**Comment by whit537** [comment]
Alright, the way I'm interpreting this ticket is that we want a new mode type `sns` that would look like:

```yaml
policies:
  - name: s3-encryption
    resource: s3
    mode:
      type: sns
      topic: arn:aws:sns:region-0:123456789012:some-topic
    action: attach-encrypt
```

Is that the right track here, @kapilt?

**Comment by kapilt** [comment]
for an initial pull request you can ignore the policy side, and just focus on mu.py support for a lambda event source on sns, there's several others there and then corresponding unit test in test_mu.py.

for a followup, the policy side here wouldn't be mode triggered, attach encrypt independently of the mode provisions a lambda on the bucket, and the logic would be in there depending on the extant bucket notification configuration on using a lambda notification or attaching to extant sns notification policies.

**Comment by whit537** [comment]
@kapilt So what's the end game here? Can you give me policy yaml or sample cli invocation demonstrating the final result we're going for here? Not to launch into full implementation but for context to understand the task on #869. Thanks.

**Comment by kapilt** [comment]
for the use case around s3, the policy would just look like
```
policies:
  - name: s3-encryption
    resource: s3
    action: attach-encrypt
```

perhaps a higher bandwidth communication medium would be useful, let's try chat.

**Comment by whit537** [comment]
> provisions a lambda on the bucket, and the logic would be in there depending on the extant bucket notification configuration on using a lambda notification or attaching to extant sns notification policies.

/me reads up on http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html ...

**Comment by whit537** [comment]
> First step is adding sns support to mu.py

Ready in #869. Revisiting here ...

**Comment by whit537** [comment]
Benchmark: what happens when running the target policy currently?

```yaml
policies:
  - name: s3-encryption
    resource: s3
    action: attach-encrypt
```

```
(cloud-custodian) $ custodian run -c custodian.yml -s .
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/cli.py", line 319, in main
    command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/commands.py", line 44, in _load_policies
    policies = policy_load(options, options.config)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 62, in load
    raise Exception("Failed to validate on policy %s \n %s" % (errors[1], errors[0]))
Exception: Failed to validate on policy s3-encryption 
 Additional properties are not allowed ('action' was unexpected)

Failed validating 'additionalProperties' in schema[78]['allOf'][0]:
    {'additionalProperties': False,
     'properties': {'actions': {'type': 'array'},
                    'comment': {'type': 'string'},
                    'comments': {'type': 'string'},
                    'description': {'type': 'string'},
                    'filters': {'type': 'array'},
                    'max-resources': {'type': 'integer'},
                    'mode': {'$ref': '#/definitions/policy-mode'},
                    'name': {'pattern': '^[A-z][A-z0-9]*(-[A-z0-9]*[A-z][A-z0-9]*)*$',
                             'type': 'string'},
                    'query': {'items': {'maxProperties': 1,
                                        'minProperties': 1,
                                        'type': 'object'},
                              'type': 'array'},
                    'region': {'type': 'string'},
                    'resource': {'type': 'string'},
                    'source': {'enum': ['describe', 'config']},
                    'tags': {'items': {'type': 'string'},
                             'type': 'array'}},
     'required': ['name', 'resource'],
     'type': 'object'}

On instance:
    {'action': 'attach-encrypt', 'name': 's3-encryption', 'resource': 's3'}
(cloud-custodian) $
```

**Comment by whit537** [comment]
```
policies:
  - name: s3-encryption
    resource: s3
    actions:
      - attach-encrypt
```

```
(cloud-custodian) $ custodian run -c custodian.yml -s .
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/cli.py", line 319, in main
    command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/commands.py", line 44, in _load_policies
    policies = policy_load(options, options.config)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 63, in load
    return PolicyCollection(data, options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 76, in __init__
    Policy(p, options, session_factory=self.test_session_factory()))
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 489, in __init__
    self.resource_manager = self.get_resource_manager()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 586, in get_resource_manager
    return factory(self.ctx, self.data)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 92, in __init__
    super(S3, self).__init__(ctx, data)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 246, in __init__
    super(QueryResourceManager, self).__init__(data, options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/manager.py", line 47, in __init__
    self.data.get('actions', []), self)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/actions.py", line 39, in parse
    results.append(self.factory(d, manager))
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/actions.py", line 58, in factory
    return action_class(data, manager).validate()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 612, in validate
    "attach-encrypt: role must be specified either "
ValueError: attach-encrypt: role must be specified either via assume or in config
(cloud-custodian) $
```

**Comment by whit537** [comment]
```yaml
policies:
  - name: s3-encryption
    resource: s3
    actions:
      - type: attach-encrypt
        role: arn:aws:iam::644160558196:role/custodian-mu
```

```
(cloud-custodian) $ custodian run -c custodian.yml -s .
2017-02-07 05:55:57,947: custodian.policy:INFO Running policy s3-encryption resource: s3 region:default c7n:0.8.22.0
2017-02-07 05:56:02,404: custodian.policy:INFO policy: s3-encryption resource:s3 has count:8 time:4.46
2017-02-07 05:56:04,289: custodian.lambda:INFO Publishing custodian policy lambda function c7n-s3-encrypt
2017-02-07 05:56:10,408: custodian.lambda:INFO Publishing custodian policy lambda function c7n-s3-encrypt
2017-02-07 05:56:17,033: custodian.s3:ERROR Error attaching lambda-encrypt An error occurred (InvalidArgument) when callin
g the PutBucketNotificationConfiguration operation: The notification destination service region is not valid for the bucke
t location constraint
None
2017-02-07 05:56:22,897: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 240, in run
    results = a.process(resources)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 665, in process
    results.append(f.result())
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/concurrent/futures/_base.py", line
 398, in result
    return self.__get_result()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/concurrent/futures/thread.py", lin
e 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 672, in process_bucket
    return source.add(func)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 907, in add
    Bucket=self.bucket['Name'], NotificationConfiguration=notifies)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: The notification destination service region is not valid for the bucket location constraint
2017-02-07 05:56:22,901: custodian.commands:ERROR Error while executing policy s3-encryption, continuing
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/commands.py", line 141, in run
    policy()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 572, in __call__
    return mode.run()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 240, in run
    results = a.process(resources)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 665, in process
    results.append(f.result())
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/s3.py", line 672, in process_bucket
    return source.add(func)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 907, in add
    Bucket=self.bucket['Name'], NotificationConfiguration=notifies)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: The notification destination service region is not valid for the bucket location constraint
(cloud-custodian) $
```

**Comment by whit537** [comment]
Success?

```yaml
policies:
  - name: s3-encryption
    resource: s3
    filters:
      - Name: whit537-297
    actions:
      - type: attach-encrypt
        role: arn:aws:iam::644160558196:role/custodian-mu
```

```
(cloud-custodian) $ custodian run -c custodian.yml -s . --region=us-west-2
2017-02-07 06:04:27,152: custodian.policy:INFO Running policy s3-encryption resource: s3 region:us-west-2 c7n:0.8.22.0
2017-02-07 06:04:27,153: custodian.policy:INFO policy: s3-encryption resource:s3 has count:1 time:0.00
2017-02-07 06:04:29,979: custodian.lambda:INFO Bucket lambda notification present
2017-02-07 06:04:30,038: custodian.policy:INFO policy: s3-encryption action: attachlambdaencrypt resources: 1 execution_time: 2.88
(cloud-custodian) $
```

**Comment by whit537** [comment]
Alright, so what did that actually do? And what do we want to be done differently?

**Comment by whit537** [comment]
> Bucket lambda notification present

My interpretation of https://github.com/capitalone/cloud-custodian/issues/297#issuecomment-275641802 is that we want to use an sns notification on the bucket instead of a lambda notification.

**Comment by whit537** [comment]
> attach-encrypt should support bucket sns notification

Alright, I'm pretty sure this means we want to support the new `SNSSubscription` from #869 as an event source in addition to [`BucketNotification` in `s3crypt`](https://github.com/capitalone/cloud-custodian/blob/22101c4aa5c2c8171324c226fa7e0efe9a519890/c7n/ufuncs/s3crypt.py#L81-L84).

**Comment by whit537** [comment]
Moving to PR in #910 ...

**Comment by kapilt** [comment]
@whit537 pls can we chill on the blow blow, it spams every project watcher, who probably don't want to line by line policy construction and validation errors.

**Comment by kapilt** [comment]
re what it did, it provisioned a lambda function that will encrypt objects as they are added to the bucket. it did so by setting a bucket notification. extant buckets may already have a bucket notification in which case this won't work, per s3 bucket notification capabilities. @ocampocj i believe was looking in the case of an sns notification on a bucket to attach it.

**Comment by whit537** [comment]
D'oh! And here I thought I was leaving google-able traces for future confusees. 😜

I'll dial it back.

**Comment by whit537** [comment]
@kapilt Do you want automatic fallback to sns if a bucket notification lambda is already present? Or explicit `events` in the policy? Or both? Or ... ?

```
policies:
  - name: s3-encryption
    resource: s3
    filters:
      - Name: whit537-297
    actions:
      - type: attach-encrypt
        role: arn:aws:iam::644160558196:role/custodian-mu
        events: []
```

**Comment by kapilt** [comment]
+ @ocampocj   for confirm on behavior ... so i think this gets a bit gray quickly, i think the request came as can we look at the existing notifications on the bucket and for topics already extant by path, and attach ourselves to them. if there is no notification set on the bucket we either want to continue as before with a lambda notify or create an sns topic for the bucket and attach ourselves.

note the event afaicr is slightly different which means ufuncs/s3crypt will need to disambiguate between the two styles (direct bucket invoke of lambda, and relayed through sns).

**Comment by ocampocj** [comment]
@kapilt after looking through some of the data we have, this is clearly becoming much more of an outlier scenario.  from an implementation point of view, I think we should be able to scan for existing SNS notifications and attach the lambda or create a new SNS notification and attach the lambda if one doesn't exist.

**Comment by whit537** [comment]
> I think we should be able to scan for existing SNS notifications and attach the lambda or create a new SNS notification and attach the lambda if one doesn't exist.

Okay, this makes it sound like we are dropping bucket notifications entirely. Yes? _Only_ SNS?

**Comment by ocampocj** [comment]
sorry @whit537, I was trying to expand on @kapilt 's previous comment but it came out strangely.  under normal circumstances, we should continue with the status quo and attach the lambda.  that would be the 'default' behavior.  however, we should also be able to specify in a policy that we would like to attach the lambda via SNS, in which case, we should be able to attach to an existing SNS or create one in the event that one doesn't already exist.

**Comment by whit537** [comment]
> we should also be able to specify in a policy that we would like to attach the lambda via SNS

Any guidance on policy schema for this? Proposal:

```yaml
policies:
  - name: s3-encryption
    resource: s3
    filters:
      - Name: whit537-297
    actions:
      - type: attach-encrypt
        role: arn:aws:iam::644160558196:role/custodian-mu
        attach_via: 'sns'
```

**Comment by whit537** [comment]
> we should be able to attach to an existing SNS

How do we pick the existing topic? Any topic with `s3:ObjectCreate:*? A topic w/ an expected name? ... ?

**Comment by ocampocj** [comment]
example policy looks good.  though, if role is not specified, does it have a default?  role doesn't need to be specified when normally creating lambdas via policy, but is it needed for sns?  

I think the lambda should attach to any existing sns if the topic already has 's3:ObjectCreate:*'.  otherwise, I think the policy (or policies) would get pretty complex having to cite different sns topic names.

**Comment by whit537** [comment]
> role doesn't need to be specified when normally creating lambdas via policy, but is it needed for sns?

From what I can see, role _does_ need to be specified for normal lambda creation. It's the role the Lambda runs as, so it's necessary in either case (unless I'm missing something?).

**Comment by whit537** [comment]
> From what I can see

https://github.com/capitalone/cloud-custodian/issues/297#issuecomment-277964822

**Comment by ocampocj** [comment]
ok, makes sense.  it didn't look like it was a required field in the schema, but from your error it definitely seems so.

https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L639

**Comment by whit537** [comment]
> it didn't look like it was a required field in the schema

Ah, good point. Maybe I can work that into this PR ...

**Comment by whit537** [comment]
> Maybe I can work that into this PR ...

Actually, we already have a [test](https://github.com/capitalone/cloud-custodian/blob/9826826b1149e3b97fe806073ba67a75544c37e7/tests/test_s3.py#L615-L620) for the `ValueError` that results from not providing `role`. My hunch is that we don't enforce `role` in the schema, because it can [also](https://github.com/capitalone/cloud-custodian/blob/9826826b1149e3b97fe806073ba67a75544c37e7/c7n/resources/s3.py#L654) be provided by `--assume`. 👍
