### ISSUE TITLE
c7n-mailer: Slack message for elasticsearch resource results in ValueError: Expecting ',' delimiter

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2986]
I'm trying to send a Slack message for the `elasticsearch` resource using the mailer.

**mailer.yml**
```
queue_url: https://sqs.us-east-1.amazonaws.com/<account_id>/cloud-cloudcustodian
from_address: <email_address>
contact_tags:
  - OwnerContact
  - OwnerEmail
  - SNSTopicARN
region: us-east-1
role: arn:aws:iam::<account_id>:role/CloudCustodian
slack_token: <token>
```

**Policy action**
```
 actions:
      - type: notify
        template: elasticsearch-security-audit.html
        slack_template: slack-elasticsearch-security-audit
        template_format: 'html'
        priority_header: '5'
        subject: 'ElasticSearch Security Audit: ES Domain found out of compliance'
        to:
          - <email_address>
          - slack://#<channel_name>
        owner_absent_contact:
          - <email_address>
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/<account_id>/cloud-cloudcustodian
```

**slack-elasticsearch-security-audit.j2**
```
{
   "attachments":[
      {
         "fallback":"Cloud Custodian Policy Violation",
         "title":"ElasticSearch Security Audit",
         "color":"danger",
         "fields":[
            {
               "title":"ES Domain",
               "value":"{%- for resource in resources -%}
                        {{ format_resource(resource, policy['resource']) }}
                        {%- endfor -%}"
            },
            {
               "title":"Account",
               "value":"{{ account }}"
            },
            {
               "title":"Region",
               "value":"{{ region }}"
            },
            {
               "title":"Action Description",
               "value":"Email notification sent."
            }
         ]
      }
   ],
   "channel":"{{ recipient }}",
   "username":"Custodian"
}
```

**Custodian run with debug**
```
(c7n_mailer) $ custodian run -s output -v elasticsearch-security-audit.yml
2018-10-11 23:27:48,040: custodian.commands:DEBUG Loaded file elasticsearch-security-audit.yml. Contains 1 policies
2018-10-11 23:27:48,044: custodian.aws:DEBUG using default region:us-east-1 from boto
2018-10-11 23:27:48,161: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:output/elasticsearch_security_audit>
2018-10-11 23:27:48,161: custodian.policy:INFO Provisioning policy lambda elasticsearch_security_audit
2018-10-11 23:27:48,210: custodian.lambda:DEBUG Created custodian lambda archive size: 1.72mb
2018-10-11 23:27:48,275: custodian.lambda:INFO Publishing custodian policy lambda function custodian-elasticsearch_security_audit
2018-10-11 23:27:48,918: custodian.lambda:DEBUG Publishing custodian lambda alias current
2018-10-11 23:27:49,083: custodian.lambda:DEBUG Added lambda invoke cwe rule permission
```

**CloudWatch logs**
```
START RequestId: 6e335dbb-cda8-11e8-bc92-09ca84966617 Version: $LATEST
[WARNING]	2018-10-11T22:53:16.117Z	6e335dbb-cda8-11e8-bc92-09ca84966617	Error: An error occurred (InvalidCiphertextException) when calling the Decrypt operation: Unable to decrypt slack_token with kms, will assume plaintext.
Traceback (most recent call last):
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 174, in process_sqs_message
slack_delivery.slack_handler(sqs_message, slack_messages)
File "/var/task/c7n_mailer/slack_delivery.py", line 103, in slack_handler
json.loads(payload, strict=False)["channel"])
File "/usr/lib64/python2.7/json/__init__.py", line 352, in loads
return cls(encoding=encoding, **kw).decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 11 column 4 (char 260)
END RequestId: 6e335dbb-cda8-11e8-bc92-09ca84966617
REPORT RequestId: 6e335dbb-cda8-11e8-bc92-09ca84966617	Duration: 11703.22 ms	Billed Duration: 11800 ms Memory Size: 1024 MB	Max Memory Used: 60 MB	
```

**Comment by thisisshi** [comment]
@davidclin what version of custodian are you running?

**Comment by davidclin** [comment]
I'm running:
```
(c7n_mailer) $ custodian version
0.8.30.0
```
I just did a pull and see the same version number (0.8.30.0) but know the pull contains lots of new updates in it so it should be the latest. Aside, is there another command I can use to confirm I'm using the latest version?

Now, when I update the mailer and re-run my policy, the delimiter error clears and I don't see any errors in the CloudWatch (CW) logs now.  Unfortunately, I'm still not getting a Slack notification and have no idea why now. The CW logs for the lambda and mailer both look fine.

I re-run an existing lambda policy that uses the s3 resource with Slack notification and confirmed I'm able to get a Slack notification just to confirm I didn't break anything. The CW logs for that policy look almost identical to the elasticsearch policy.

Fortunately, the issue is very easy to reproduce.

You can create a Public ElasticSearch domain with wide open permissions then run the policy I'm using below to reproduce the problem:

**To create a Public Elasticsearch domain, go to the ElasticSearch console:** 
1) Click **Create a new domain**
2) Provide an ES name 
3) Use default ES version (ie 6.3)
4) Click **Next**
5) Use all provided defaults (no need to add anything on this page)
6) Click **Next**
7) Click **Public access** (this is the important part, because this is what I'm trying to audit)
8) Leave all other options as default (no need to add anything)
9) Click **Select a template** and choose **Allow access to the domain**
10) Click **I accept the risk** then **OK**
11) Click **Next**
12) Click **Confirm**

**Run the following policy with appropriate Slack token**
```
policies:
  - name: elasticsearch_security_audit
    resource: elasticsearch
    description: |
      Cloud Custodian Elasticsearch Security Audit
    comments: |
      Periodically check PUBLIC ES domains that have
      access policies that are too permissive.
      Ignore PRIVATE ES domains.
      PRIVATE domains will have VPCOptions configured.
      PUBLIC  domains will have a Condition with AccessApolicies configured.
      Send email/Slack notification.
    mode:
      type: periodic
      role: arn:aws:iam::<account_id>:role/CloudCustodian
      schedule: "rate(5 minutes)"
    filters:
      - type: value
        key: VPCOptions
        value: null
      - or:
        - not:
          - type: value
            key: AccessPolicies
            op: regex
            value: .*Condition.*
        - type: value
          key: AccessPolicies
          op: regex
          value: .*0.0.0.0/0.*
    actions:
      - type: notify
        slack_template: slack-elasticsearch-security-audit
        template_format: 'html'
        priority_header: '5'
        subject: 'ElasticSearch Security Audit: ES Domain found out of compliance'
        to:
          - <email_address>
          - slack://#<channel_name>
        owner_absent_contact:
          - <email_address>
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/<account_id>/cloud-cloudcustodian
```

**Jinja2 Template (slack-elasticsearch-security-audit.j2)**
```
{
   "attachments":[
      {
         "fallback":"Cloud Custodian Policy Violation",
         "title":"ElasticSearch Security Audit",
         "color":"danger",
         "fields":[
            {
               "title":"ES Domain",
               "value":"{%- for resource in resources -%}
                        {{ format_resource(resource, policy['resource']) }}
                        {%- endfor -%}"
            },
            {
               "title":"Account",
               "value":"{{ account }}"
            },
            {
               "title":"Region",
               "value":"{{ region }}"
            },
            {
               "title":"Action Description",
               "value":"Email notification sent."
            }
         ]
      }
   ],
   "channel":"{{ recipient }}",
   "username":"Custodian"
}
```

For this particular use case, the ES domain created will not have an `AccessPolicies` key with value `.*Condition.*`. That will trigger the Slack notification.

**Comment by thisisshi** [comment]
Is the s3 policy that you tested using the same template as the elasticsearch policy? I wonder if there's a problem in assembling the template from the resource json object that gets passed in

**Comment by davidclin** [comment]
I use a vanilla Slack template for all my policies and just change the titles like so:
```{
   "attachments":[
      {
         "fallback":"Cloud Custodian Policy Violation",
         "title":"Public S3 Bucket Audit",
         "color":"danger",
         "fields":[
            {
               "title":"S3 Bucket Name",
               "value":"{%- for resource in resources -%}
                        {{ format_resource(resource, policy['resource']) }}
                        {%- endfor -%}"
            },
            {
               "title":"Account",
               "value":"{{ account }}"
            },
            {
               "title":"Region",
               "value":"{{ region }}"
            },
            {
               "title":"Action Description",
               "value":"Email notification sent."
            }
         ]
      }
   ],
   "channel":"{{ recipient }}",
   "username":"Custodian"
}
```

**Comment by davidclin** [comment]
I think you're onto something. If I replace the resource json object with a string, the Slack msg is received successfully, of course, without any information related to the resource which would be useful.

**Comment by davidclin** [comment]
Here's the decode of the msg containing `resources` when I pull it out of SQS:
```
...
"resources": [
{
"ElasticsearchClusterConfig": {
"DedicatedMasterEnabled": false,
"InstanceCount": 1,
"ZoneAwarenessEnabled": false,
"InstanceType": "m4.large.elasticsearch"
},
"Endpoint": "search-public-<randomstring>.us-east-1.es.amazonaws.com",
"CognitoOptions": {
"Enabled": false
},
"Created": true,
"Deleted": false,
"DomainName": "public",
"EBSOptions": {
"VolumeSize": 10,
"VolumeType": "gp2",
"EBSEnabled": true
},
"c7n:MatchedFilters": [
"VPCOptions",
"AccessPolicies"
],
"SnapshotOptions": {
"AutomatedSnapshotStartHour": 0
},
"DomainId": "<account_id>/public",
"AccessPolicies": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"} ,\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:us-east-1:<account_id>:domain/public/*\",\"Condition\":{\"IpAddres s\":{\"aws:SourceIp\":\"0.0.0.0/0\"}}}]}",
"Processing": false,
"Tags": [],
"AdvancedOptions": {
"rest.action.multi.allow_explicit_index": "true"
},
"EncryptionAtRestOptions": {
"Enabled": false
},
"ElasticsearchVersion": "6.3",
"ARN": "arn:aws:es:us-east-1:<account_id>:domain/public"
}
]
```

**Comment by thisisshi** [comment]
@davidclin Yeah, I think it's happening because the AccessPolicies string is not being rendered correctly and silently erroring out, can you try sending a slack message with a resource that doesn't have the AccessPolicies key?

**Comment by davidclin** [comment]
Ok, I think I'm getting closer.

I tried the following and am getting slack messages (but no values).
Below is an example where I try and match against the key `AccessPolicies`:

```
{
   "attachments":[
      {
         "fallback":"Cloud Custodian Policy Violation",
         "title":"ElasticSearch Security Audit",
         "color":"danger",
         "fields":[
            {
               "title":"Test",
               "value":"{{ AccessPolicies }}"  <-- also tried DomainId, DomainName, and ARN
            },
            {
               "title":"Account",
               "value":"{{ account }}"
            },
            {
               "title":"Region",
               "value":"{{ region }}"
            },
            {
               "title":"Action Description",
               "value":"Email notification sent. See email for details."
            }
         ]
      }
   ],
   "channel":"{{ recipient }}",
   "username":"Cust

I then tried `DomainId`, `DomainName`, and `ARN` which also returned no values.
I wonder if I'm using the wrong keynames? My understanding was I could reference any of the keys mentioned under `resources` in the sqs msg. I've also tried lowercase key names but those return no values in the slack message.

Am I looking in the right place for the key names?
I'm primarily interested in getting the ES DomainId, ARN, and/or DomainName if the AccessPolicies is too complicated. Any of the other keys will be sufficient for what I need for this use case.

**Comment by davidclin** [comment]
I forgot to answer the initial question. 
The answer is, yes, I'm able to get slack messages when sending with a resource that doesn't have the AccessPolicies key. :)

**Comment by davidclin** [comment]
Just tried 
```
            {
               "title":"Test",
               "value":"{{ resources }}"  
            },
```
for the ES resource and the slack msg stopped right away.

**Comment by epluscloudservices** [comment]
Thanks. My workaround is to use an email notification that's able to retrieve the `AccessPolicies` and use the Slack notification as a visual indicator to go and check the email for the details. 

More than happy to test the fix whenever it becomes available.

**Comment by kapilt** [comment]
this seems more like escaping the access policy when rendering in template.
