### ISSUE TITLE
Assumed role not being passed into lambda config

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#3006]
Getting this error on trunk:

```
2018-10-19 01:10:12,112: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
File "/src/c7n/policy.py", line 494, in provision
role=self.policy.options.assume_role)
File "/src/c7n/mu.py", line 283, in publish
func, role, s3_uri, qualifier=alias)
File "/src/c7n/mu.py", line 427, in _create_or_update
result = self.client.update_function_configuration(**new_config)
File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationException) when calling the UpdateFunctionConfiguration operation: 1 validation error detected: Value '' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
```

Related to this change: https://github.com/capitalone/cloud-custodian/commit/e012885d86cd5492a364bfa4b50750515e32a97e#diff-3b6d052df3306ec5a910d7c6055b0e57L417

**Comment by kapilt** [comment]
specifically this is using custodian being run with lambda policy with role automatically provided per the assume role value i think?

**Comment by thisisshi** [comment]
@kapilt yes
