### ISSUE TITLE
Azure - Errors Running Event Grid Functions

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#3023]
### Description: 
Errors appear when attempting to run the default example of Event Grid Function on the Azure documentation page. The documentation surrounding this could be more robust, it doesn't indicate what items from 'mode' from the other example templates using functions can be used with event grid functions (are all inherited?). I have tried the default policy as well as running a policy where I specify the appInsights, and StorageAccount, both custodian runs fail pointing to async_abc.py:

```
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/msrest/universal_http/async_abc.py", line 34
    async def __aenter__(self):
```

Details below.

#### New Virtualenv setup: 
```
pip install c7n
pip install c7n_azure
```
#### Policy 1 being run:
```
policies:
    - name: tag-key-vault-creator
      resource: azure.keyvault
      mode:
        type: azure-event-grid
        events: [{
            resourceProvider: 'Microsoft.KeyVault/vaults',
            event: 'write'
          }]
      filters:
        - "tag:CreatorEmail": null
      actions:
        - type: auto-tag-user
          tag: CreatorEmail
          days: 10
```
#### Policy 2 Terminal Output: 
```
(currentDirectory) ➜   git:(master) ✗ custodian run --output-dir=. eventgridtest.yml
2018-10-23 08:50:36,839: custodian.azure.session:INFO Creating session with Azure CLI Authentication
2018-10-23 08:50:36,840: custodian.azure.session:INFO Session using Subscription ID:subscriptionID
2018-10-23 08:50:37,990: custodian.azure.function_app_utils:INFO Found Web Application "cloud-custodian-tag-key-vault-creator".
2018-10-23 08:50:37,990: custodian.azure.AzureFunctionMode:INFO Building function package for cloud-custodian-tag-key-vault-creator
2018-10-23 08:50:39,874: custodian.commands:ERROR Error while executing policy tag-key-vault-creator, continuing
Traceback (most recent call last):
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n/commands.py", line 232, in run
    policy()
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n/policy.py", line 870, in __call__
    resources = mode.provision()
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n_azure/policy.py", line 225, in provision
    super(AzureEventGridMode, self).provision()
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n_azure/policy.py", line 171, in provision
    archive.build(self.policy.data)
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n_azure/function_package.py", line 151, in build
    modules, so_files = FunctionPackage._get_dependencies(entry_point)
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/c7n_azure/function_package.py", line 270, in _get_dependencies
    finder.run_script(entry_point)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 133, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 208, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 208, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 305, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 468, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 443, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/modulefinder.py", line 309, in load_module
    co = compile(fp.read()+'\n', pathname, 'exec')
  File "workingDirectory/eventgridtests/lib/python2.7/site-packages/msrest/universal_http/async_abc.py", line 34
    async def __aenter__(self):
            ^
SyntaxError: invalid syntax
```

**Comment by stefangordon** [comment]
#3024

**Comment by jdogg89** [comment]
@stefangordon 
I switched to python3 virtualenv and got better results. I see that function_binding_resources is not copying to the virtualenv path, whether I do a fresh install of the cloud-custodian repo (with the file present) and do `pip install ./cloud-custodian` and `pip install ./cloud-custodian/tools/c7n_azure` or If I pull from pypl `pip install c7n` and `pip install c7n_azure`

FileNotFoundError: [Errno 2] No such file or directory: '/home/custodian/lib/python3.5/site-packages/c7n_azure/function_binding_resources/extensions.csproj'

When I copy over the function binding resources folder from the custodian project to the virtualenv path it want it at, the function app builds successfully. Is this expexted behavior for that folder to not copy over?

**Comment by aluong** [comment]
We need to update the setup.py to bring these files over.

**Comment by erwelch** [comment]
PR out for it: https://github.com/capitalone/cloud-custodian/pull/3033

**Comment by erwelch** [comment]
The fix is in @jdogg89 - you should be able to install from github (pypi doesn't have latest changes)! Let me know if you see any other weird behaviors around the dlls.

**Comment by stefangordon** [comment]
Btw, 3.5 may not work either, it may have to be 3.6 (the python version Azure functions uses) - due to the current way we package native assemblies.

**Comment by erwelch** [comment]
3.5 definitely does not work - your function will deploy but the function will fail at runtime. I ran into this last week when I accidentally used 3.5.
