### ISSUE TITLE
Error using 'metrics_enabled' upgrading from v0.8.31.2 to v0.8.32.0

### ISSUE THREAD

**Issue by CallumHibbert** [capitalone/cloud-custodian#3138]
The update from 0.8.31.2 to 0.8.32.0 means I get an error...

AttributeError: 'Namespace' object has no attribute 'metrics_enabled'

Part of the "execution-options" when running as a Lambda.

**Comment by kapilt** [comment]
any more details on traceback or policy that trigger (sanitized on either of account details)

**Comment by CallumHibbert** [comment]
I read the logs too quickly, looks like this is an issue with "mugc.py" but I am still struggling to troubleshoot. Here is the output:

[Container] 2018/11/14 17:05:35 Running command python cloud-custodian/tools/ops/mugc.py -v --prefix mnpg-ops-custodian-policy- -c $fileList
Traceback (most recent call last):
 File "cloud-custodian/tools/ops/mugc.py", line 166, in <module>
 main()
 File "cloud-custodian/tools/ops/mugc.py", line 161, in main
 policies = load_policies(options)
 File "cloud-custodian/tools/ops/mugc.py", line 33, in load_policies
 collection = policy_load(options, f)
 File "/usr/local/lib/python3.6/site-packages/c7n/policy.py", line 77, in load
 collection = PolicyCollection.from_data(data, options)
 File "/usr/local/lib/python3.6/site-packages/c7n/policy.py", line 96, in from_data
 for p in data.get('policies', ())]
 File "/usr/local/lib/python3.6/site-packages/c7n/policy.py", line 96, in <listcomp>
 for p in data.get('policies', ())]
 File "/usr/local/lib/python3.6/site-packages/c7n/policy.py", line 691, in __init__
 self.ctx = ExecutionContext(self.session_factory, self, self.options)
 File "/usr/local/lib/python3.6/site-packages/c7n/ctx.py", line 50, in __init__
 self.metrics = metrics_outputs.select(self.options.metrics_enabled, self)
AttributeError: 'Namespace' object has no attribute 'metrics_enabled'

What I don't understand is that applying "pip install c7n==0.8.31.2" fixed this (hence my original post) but mugc.py is called from a straight clone (latest version) from the repo. I am currently clueless on the root cause.

**Comment by kapilt** [comment]
the pr in #3163 resolves this a bit better, in that it restores the previous behavior.
