### ISSUE TITLE
Allow for automated integration testing of policies

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#455]
@kapil, we should have the ability to automate policy testing using cloudformation (or other tool).  AWS resources should be spun up, the policies should run against them, and then the resources can be terminated.

**Comment by kapilt** [comment]
this sounds useful, i think its probably a standalone tool of some kind, its a little unclear what it would be doing

```
   policy.yml
   stack/       
   test.yml
   data
```

test.yml needs some notion of a stack, its format/runner, and then some notion of validating the output.

**Comment by whit537** [comment]
From https://github.com/capitalone/cloud-custodian/issues/62#issuecomment-271050126:

> Ideally we'd actually _run_ the policies automatically to make sure the examples still work, but that would require probably another yaml block specifying a fixture policy to put AWS into the state assumed by the target yaml itself.

--------------

> a few users expressed interest in having a policy test runner, which would actually do something like that, by giving some fixtures (terraform or cfn) and then being able to run the policy and assert actions.

**Comment by whit537** [comment]
> cloudformation (or other tool)
> (terraform or cfn)

https://aws.amazon.com/cloudformation/
https://www.terraform.io/docs/providers/aws/

**Comment by whit537** [comment]
Started messing around with this. Setting up fixture via CloudFormation and running Custodian against it is easy enough. The missing piece for me is comprehending resulting state so we can diff our expectation against it. Can one export an AWS state back to a CloudFormation json/yaml description?

**Comment by whit537** [comment]
http://stackoverflow.com/questions/24740405/take-backup-of-aws-configuration-across-all-services
http://stackoverflow.com/questions/38057526/aws-export-configuration-as-cloudformation-template
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html
https://github.com/arminhammer/bellerophon

**Comment by kapilt** [comment]
i was thinking the validation would be another custodian policy ;-)

**Comment by whit537** [comment]
Starting working this in https://github.com/whit537/cloud-custodian/commit/5f2e8ff7d3868f27b826679e5d8d971a64a66b45, but I'm running up against IAM perms [again](https://github.com/capitalone/cloud-custodian/issues/802#issuecomment-270345116):

```
(cloud-custodian) $ nosetests -s tests/integration/test_something.py 

[…]

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/integration/test_something.py", line 46, in setUpClass
    TemplateURL='https://s3.amazonaws.com/cloudformation-examples/AWSCloudFormer.template'
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/integration/test_something.py", line 29, in create_stack
    response = cls.cfn.create_stack(StackName=name, **kw)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_IAM]
-------------------- >> begin captured logging << --------------------
```

**Comment by kapilt** [comment]
this is more about aws cfn basics.. you have to pass --capabilities CAPABILITY_IAM on the cli, or equivalent in the api when creating the stack. lmgtfy ;-)

**Comment by whit537** [comment]
PR in #836.

**Comment by whit537** [comment]
https://aws.amazon.com/organizations/

**Comment by whit537** [comment]
And cf. #903.

**Comment by whit537** [comment]
Organizations [hit GA on Feb 27](https://aws.amazon.com/about-aws/whats-new/2017/02/aws-organizations-now-generally-available/).

**Comment by kiwiz** [comment]
I'm interested in this functionality from a slightly different angle. When developing policies, it's helpful to have a static dump of API calls to test against. This insulates us from changes due to actions on cloud resources & speeds up iteration (no need to wait on API calls & you can inspect the response).

Looking at the docs, the `record_flight_data` functionality appears to do almost everything we'd need. Is there any interest in extract that functionality out and making it accessible via the main `custodian run` command? If not, I'd still like to submit a PR to add `assume_role` support to the `PillTest` class.
