### ISSUE TITLE
using config-rule on an unsupported resource should result in a validation error

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#508]
at the moment its a attr error on config type on the resource meta model.

**Comment by kapilt** [comment]
from gitter user report

```
policies:
  - name: cloudtrail_enabled
    description: |
      Ensure CloudTrail is enabled in all regions and encrypted
    resource: account
    mode:
      type: config-rule
    filters:
      - type: check-cloudtrail
        multi-region: true
        kms: True
```
the tracback I get is:

```
2016-10-10 14:08:13,742: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/opt/c7n/lib/python2.7/site-packages/c7n/policy.py", line 295, in provision
    role=self.policy.options.assume_role)
  File "/opt/c7n/lib/python2.7/site-packages/c7n/mu.py", line 227, in publish
    if e.add(func):
  File "/opt/c7n/lib/python2.7/site-packages/c7n/mu.py", line 1030, in add
    params = self.get_rule_params(func)
  File "/opt/c7n/lib/python2.7/site-packages/c7n/mu.py", line 998, in get_rule_params
    config_type = manager.get_model().config_type
  File "/opt/c7n/lib/python2.7/site-packages/c7n/manager.py", line 71, in get_model
    return self.query.resolve(self.resource_type)
AttributeError: 'Account' object has no attribute 'query'
```

**Comment by kapilt** [comment]
currently validation is implicit on construction and limited to filters and actions, we'll need to make it explicit and a method on a policy that the policy can validate mode on and propagate to filters and actions.

**Comment by kapilt** [comment]
merged
