### ISSUE TITLE
S3 - `attach-encrypt` Action doesn't deploy Lambda in non-useast1 regions

### ISSUE THREAD

**Issue by mandeepbal** [capitalone/cloud-custodian#542]
The policy below fails when I execute against the `us-west-2` region. My bucket is in `us-west-2`, but when i execute custodian it does not deploy the `s3-encrypt` lambda function. It does however try to attach a non-existent function (`arn:aws:lambda:us-west-2:0000000000:function:c7n-s3-encrypt`) in the logs.
### Policy:

```
policies:
  - name: s3-lambda-bucket-encrypt-all-the-things
    resource: s3
    filters:
      - type: value
        key: Name
        op: in 
        value:
         - my-west2-bucket-1
         - my-west2-bucket-2
         - my-west2-bucket-3
    actions:
      - attach-encrypt
```
### Logs

```
2016-10-21 02:14:20,760: custodian.policy:INFO policy: s3-lambda-bucket-encrypt-all-the-things resource:s3 has count:1 time:40.78
2016-10-21 02:14:23,381: custodian.s3:ERROR Error attaching lambda-encrypt An error occurred (ResourceNotFoundException) when calling the AddPermission operation: Function not found: arn:aws:lambda:us-west-2:0000000000:function:c7n-s3-encrypt
None
2016-10-21 02:14:23,383: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 192, in run
    results = a.process(resources)
  File "/usr/local/custodian/local/lib/python2.7/site-packages/c7n/resources/s3.py", line 451, in process
    results.append(f.result())
  File "/usr/local/custodian/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/custodian/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/custodian/local/lib/python2.7/site-packages/c7n/resources/s3.py", line 457, in process_bucket
    return source.add(f)
  File "/usr/local/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 871, in add
    lambda_client.add_permission(**params)
  File "/usr/local/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ResourceNotFoundException) when calling the AddPermission operation: Function not found: arn:aws:lambda:us-west-2:0000000000:function:c7n-s3-encrypt
```

**Comment by kapilt** [comment]
fixed in #563
