### ISSUE TITLE
Security Group filter "used" does not work correctly.

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#555]
If I use the following policy:

```
policies:
  - name: default-sg-allows-all-traffic
    description: |
      Find whether the default security group allows all traffic.
    resource: security-group
    filters:
      - type: used
```

I get the following error:

```
Traceback (most recent call last):
  File "/Users/laiello58/Development/git/cloud-custodian-policies/env/lib/python2.7/site-packages/c7n/policy.py", line 162, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/laiello58/Development/git/cloud-custodian-policies/env/lib/python2.7/site-packages/c7n/query.py", line 152, in resources
    return self.filter_resources(resources)
  File "/Users/laiello58/Development/git/cloud-custodian-policies/env/lib/python2.7/site-packages/c7n/manager.py", line 63, in filter_resources
    resources = f.process(resources, event)
  File "/Users/laiello58/Development/git/cloud-custodian-policies/env/lib/python2.7/site-packages/c7n/resources/vpc.py", line 178, in process
    unused = set(self.filter_peered_refs(unused))
TypeError: unhashable type: 'dict'
2016-10-27 13:31:13,308: custodian.commands:WARNING Error while executing policy default-sg-allows-all-traffic, continuing
```

I should also note that the `unused` filter works perfectly fine.

**Comment by kapilt** [comment]
Noted, thanks
