### ISSUE TITLE
WAF unit test failure

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#604]
```
$ make test
AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-east-1 ./bin/nosetests  --processes=-1 tests
.......................................................................................................................................................................................................................................................................................................................................................................................E..................
======================================================================
ERROR: test_waf_query (tests.test_waf.WAFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/tests/test_waf.py", line 12, in test_waf_query
    resources = p.run()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/policy.py", line 463, in __call__
    return mode.run()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/policy.py", line 167, in run
    resources = self.policy.resource_manager.resources()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/query.py", line 161, in resources
    resources = self.query.filter(self.resource_type, **query)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/query.py", line 62, in filter
    data = results.build_full_result()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 290, in build_full_result
    for response in self:
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Missing required parameter in input: "Limit"
-------------------- >> begin captured logging << --------------------
placebo.pill: DEBUG: attaching to session: Session(region_name='us-east-1')
placebo.pill: DEBUG: datapath: /home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/tests/data/placebo/test_waf_query
c7n.cache: DEBUG: Disabling cache
custodian.output: DEBUG: Storing output with <DirectoryOutput to dir:/tmp/tmpSyguVw/waftest>
custodian.policy: INFO: Running policy waftest resource: waf region:us-east-1 c7n:0.8.20.1
placebo.pill: DEBUG: _create_client
custodian.output: ERROR: Error while executing policy
Traceback (most recent call last):
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/policy.py", line 167, in run
    resources = self.policy.resource_manager.resources()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/query.py", line 161, in resources
    resources = self.query.filter(self.resource_type, **query)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/c7n/query.py", line 62, in filter
    data = results.build_full_result()
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 290, in build_full_result
    for response in self:
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/kit/wrk/src/github.com/ewbankkit/cloud-custodian/local/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Missing required parameter in input: "Limit"
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 394 tests in 9.431s

FAILED (errors=1)
Makefile:22: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by kapilt** [comment]
update your botocore version

**Comment by ewbankkit** [comment]
```
$ pip install --upgrade botocore
Collecting botocore
  Downloading botocore-1.4.70-py2.py3-none-any.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 624kB/s 
Collecting python-dateutil<3.0.0,>=2.1 (from botocore)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 4.6MB/s 
Requirement already up-to-date: docutils>=0.10 in ./lib/python2.7/site-packages (from botocore)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in ./lib/python2.7/site-packages (from botocore)
Requirement already up-to-date: six>=1.5 in ./lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore)
Installing collected packages: python-dateutil, botocore
  Found existing installation: python-dateutil 2.5.3
    Uninstalling python-dateutil-2.5.3:
      Successfully uninstalled python-dateutil-2.5.3
  Found existing installation: botocore 1.4.57
    Uninstalling botocore-1.4.57:
      Successfully uninstalled botocore-1.4.57
Successfully installed botocore-1.4.70 python-dateutil-2.6.0
(cloud-custodian) kit@lub1604x64-dev:~/wrk/src/github.com/ewbankkit/cloud-custodian$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-east-1 ./bin/nosetests  --processes=-1 tests/test_waf.py
.
----------------------------------------------------------------------
Ran 1 test in 0.085s

OK
```
