### ISSUE TITLE
cloudtrail event throws error

### ISSUE THREAD

**Issue by amphibithen** [capitalone/cloud-custodian#846]
policy.yml
```
policies:
  - name: asg-requires-tag-costCenter
    resource: asg
    description:
      if costCenter tag is missing, delete asg
    mode:
      type: cloudtrail
      events:
        - PutScalingPolicy
      role: arn:aws:iam::123:role/abc
    filters:
     - "tag:costCenter": absent
    actions:
     - type: delete
```

error log
```
2017-01-12 21:14:00,988: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:/var/log/cloud-custodian/asg-requires-tag-costCenter>
2017-01-12 21:14:00,988: custodian.policy:INFO Provisioning policy lambda asg-requires-tag-costCenter
2017-01-12 21:14:01,036: custodian.lambda:DEBUG Created custodian lambda archive size: 1.24mb
2017-01-12 21:14:01,374: custodian.lambda:DEBUG Updating cwe rule for <CWEvent Type:cloudtrail Events:PutScalingPolicy>
2017-01-12 21:14:01,403: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 354, in provision
    role=self.policy.options.assume_role)
  File "/src/c7n/mu.py", line 249, in publish
    if e.add(func):
  File "/src/c7n/mu.py", line 769, in add
    response = self.client.put_rule(**params)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidEventPatternException) when calling the PutRule operation: Event pattern is not valid. Reason: Empty arrays are not allowed
 at [Source: {"detail": {"eventName": ["PutScalingPolicy"], "eventSource": []}, "detail-type": ["AWS API Call via CloudTrail"]}; line: 1, column: 65]
```

but according to cloudtrail, this is a valid event.

**Comment by amphibithen** [comment]
adding the following line to mode resolved the above error:
```
      sources:
        - aws.autoscaling
```

but then the stream logs throw this error:
```
[DEBUG]	2017-01-13T21:21:51.959Z	4c6959c6-d9d6-11e6-9e18-8d52fd042a69	Disabling cache

21:21:51
[INFO]	2017-01-13T21:21:51.959Z	4c6959c6-d9d6-11e6-9e18-8d52fd042a69	Found resource ids: ()
[INFO]	2017-01-13T21:21:51.959Z	4c6959c6-d9d6-11e6-9e18-8d52fd042a69	Found resource ids: ()

21:21:51
[WARNING]	2017-01-13T21:21:51.959Z	4c6959c6-d9d6-11e6-9e18-8d52fd042a69	Could not find resource ids
[WARNING]	2017-01-13T21:21:51.959Z	4c6959c6-d9d6-11e6-9e18-8d52fd042a69	Could not find resource ids

21:21:51
END RequestId: 4c6959c6-d9d6-11e6-9e18-8d52fd042a69
END RequestId: 4c6959c6-d9d6-11e6-9e18-8d52fd042a69
```

**Comment by kapilt** [comment]
you have to spec sources ands ids. custodian has shortcuts for some events via specifying event name, lack of a shortcut should be a validation error and message. additional shortcuts welcome (cwe.py)

full example for point in time recovery on security groups which does the same on cwe for a custom set of events.
https://gist.github.com/kapilt/d5a53ae4239cecbc4e027d192423117c

**Comment by vdbrooks** [comment]
Thanks for the example @kapilt . Spec'ing the sources and ids as shown in the example worked perfectly for me.

**Comment by amphibithen** [comment]
thanks this resolved my error too.
