### ISSUE TITLE
bad error on duplicate policy

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#902]
duplicate policies should be generating a distinct error message, that seems to have been lost and is now showing a rather inscrutinable error handling bug as its trying to interpolate a duplicate policy name as a jsonschema validation error. @scotwk 

```
(custodian):custodian$ custodian run -c rdsrule.yml -s out -v
Traceback (most recent call last):
  File "/Users//projects/custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users//projects/custodian/c7n/cli.py", line 319, in main
    command(options)
  File "/Users//projects/custodian/c7n/commands.py", line 44, in _load_policies
    policies = policy_load(options, options.config)
  File "/Users//projects/custodian/c7n/policy.py", line 62, in load
    raise Exception("Failed to validate on policy %s \n %s" % (errors[1], errors[0]))
IndexError: list index out of range
```

**Comment by scotwk** [comment]
@kapilt - There is a fix on #906.
