### ISSUE TITLE
Spot Instance Filter

### ISSUE THREAD

**Issue by fathre2** [capitalone/cloud-custodian#970]
There doesn't seem to be support for the spot instance lifecycle filter.  Looking to have a policy for EC2 (normal/scheduled) and a termination policy for spot instances.    The main issue here is that any EC2 filter policy to stop instances will fail since Spot Instances cannot stop only terminate.   Would like to have two separate policies terminate for spot and stop for EC2 but need a means to filter on lifecycle.  

ec2:
  actions: [auto-tag-user, invoke-lambda, mark, mark-for-op, modify-security-groups,
    normalize-tag, notify, remove-tag, rename-tag, resize, snapshot, start, stop,
    tag, tag-trim, terminate, unmark, untag]
  filters: [and, default-vpc, ebs, ephemeral, event, image, image-age, instance-age,
    instance-uptime, marked-for-op, metrics, offhour, onhour, or, security-group,
    state-age, subnet, tag-count, value]

**Comment by fathre2** [comment]
Another Note on this one... for a base policy to stop EC2 instances...if there is a spot instance it will fail the rest of the server stops.  

2017-02-22 13:02:07,069: custodian.policy:INFO policy: offhour_stop_11 resource:ec2 has count:2 time:2.90
2017-02-22 13:02:07,215: custodian.actions:INFO Stop 2 of 2 instances
2017-02-22 13:02:07,390: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 241, in run
    results = a.process(resources)
  File "/usr/lib/python2.7/site-packages/c7n/resources/ec2.py", line 711, in process
    [i['InstanceId'] for i in persistent])
  File "/usr/lib/python2.7/site-packages/c7n/resources/ec2.py", line 717, in _run_instances_op
    return self.manager.retry(op, InstanceIds=instance_ids)
  File "/usr/lib/python2.7/site-packages/c7n/utils.py", line 288, in _retry
    return func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (UnsupportedOperation) when calling the StopInstances operation: The instance 'i-0e416212aa4d99df7' is a spot instance and may not be stopped.
2017-02-22 13:02:07,391: custodian.commands:ERROR Error while executing policy offhour_stop_11, continuing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/commands.py", line 173, in run
    policy()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 573, in __call__
    return mode.run()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 241, in run
    results = a.process(resources)
  File "/usr/lib/python2.7/site-packages/c7n/resources/ec2.py", line 711, in process
    [i['InstanceId'] for i in persistent])
  File "/usr/lib/python2.7/site-packages/c7n/resources/ec2.py", line 717, in _run_instances_op
    return self.manager.retry(op, InstanceIds=instance_ids)
  File "/usr/lib/python2.7/site-packages/c7n/utils.py", line 288, in _retry
    return func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (UnsupportedOperation) when calling the StopInstances operation: The instance 'i-0e416212aa4d99df7' is a spot instance and may not be stopped.

**Comment by kapilt** [comment]
cool, noted (we do some internal filtering on ephemeral, we can do the same on spot) is there an attribute of the instance that marks it as spot ? ie a tag with aws prefix or other intrinsic attr?

**Comment by kapilt** [comment]
i'm firing some up, will report back on it shortly.

**Comment by kapilt** [comment]
just use a filter on the tag, aws prefixed tags are not impersonatable by users, so to filter out spot instances

```
filters:
  - "tag:aws:ec2spot:fleet-request-id": absent
```

**Comment by fathre2** [comment]
Thank you!!..Will give it a try.
There is also a ec2 attribute when we have there.. 'instance-lifecycle': ('spot',),  which is present in the EC2_VALID_FILTERS

**Comment by fathre2** [comment]
Also. this is not spot fleet just traditional spot...Do not see any tags in the out put of EC2... 'instance-lifecycle': ('spot',)'

**Comment by fathre2** [comment]
Btw... we got this to work....problem solved. 

- "InstanceLifecycle": spot
